#PANDAS

In [130]:
import numpy as np
import pandas as pd

In [131]:
famoues={"india":"biryani","pak":"chicken","aus":"burger"}

In [132]:
for k,v in famoues.items():
    print(k,v)

india biryani
pak chicken
aus burger

In [133]:
pd.Series(famoues)

india    biryani
pak      chicken
aus       burger
dtype: object

In [134]:
Fruites=["Apple","Banana","Orange","Mango"]
pd.Series(Fruites)

0     Apple
1    Banana
2    Orange
3     Mango
dtype: object

In [135]:
##BY DEFAULT DTYPE IS OBJECT WHEN WE HAVE COLLECTION OR MIX D TYPE IN SAME TABLE

In [136]:
arr=[10,20,30,40,50]
pd.Series(arr)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [137]:
breakfast={"Mon":"Poha","Tues":"jalebi","Wed":"idle","Thu":"eggs","Friday":"ots","Sat":"Samosa","Sun":"chole Bhature"}
pd.Series(breakfast)

Mon                Poha
Tues             jalebi
Wed                idle
Thu                eggs
Friday              ots
Sat              Samosa
Sun       chole Bhature
dtype: object

In [138]:
days=["Mon","Thue","Wed","Thu","Fri","Sat","Sun"]
foods=["poha","jalebi","idle","dosa","rasam rice","eggs","sprauts"]

**it firstly take data after that it take indexing**

In [139]:
pd.Series(foods,days)

Mon           poha
Thue        jalebi
Wed           idle
Thu           dosa
Fri     rasam rice
Sat           eggs
Sun        sprauts
dtype: object

In [140]:
#lets try days first after data
pd.Series(days,foods)

poha           Mon
jalebi        Thue
idle           Wed
dosa           Thu
rasam rice     Fri
eggs           Sat
sprauts        Sun
dtype: object

In [141]:
#but you also use it like after swaping nothing change
pd.Series(data=foods,index=days)

Mon           poha
Thue        jalebi
Wed           idle
Thu           dosa
Fri     rasam rice
Sat           eggs
Sun        sprauts
dtype: object

In [142]:
#home work marks and students name table using list
name=["Abhay","Deepa","Mihika","Aryan","Shubham"]
marks=[91,93,90,89,85]
pd.Series(data=marks,index=name)

Abhay      91
Deepa      93
Mihika     90
Aryan      89
Shubham    85
dtype: int64

In [143]:
#now using dictnoary
marks={"Abhay":91,"Deepa":99,"Mihika":91}
markss=pd.Series(marks)
markss

Abhay     91
Deepa     99
Mihika    91
dtype: int64

**Some agrregate functions**

In [144]:
markss.sum()

np.int64(281)

In [145]:
markss.prod()

np.int64(819819)

In [146]:
markss.mean()

np.float64(93.66666666666667)

In [147]:
markss.size

3

In [148]:
markss.std()

4.618802153517006

26/03/26

In [149]:
arr=[10,20,30,40,50]
s=pd.Series(arr)
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [150]:
type(s)

pandas.core.series.Series

In [151]:
s.sum()

np.int64(150)

In [152]:
s.mean()

np.float64(30.0)

In [153]:
s.median()

30.0

In [154]:
s.size

5

In [155]:
s.max()

50

In [156]:
s.min()

10

In [157]:
s.argmax()

np.int64(4)

In [158]:
s.argmin()

np.int64(0)

In [159]:
s.idxmax()#work as argmax

4

In [160]:
s.idxmin()#work as argmin

0

In [161]:
s.std()

15.811388300841896

In [162]:
#for null value hai ki nhi
s.isnull()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [163]:
s.round()#for round figure

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [164]:
s.hasnans# for check none value

False

In [165]:
s.dtype

dtype('int64')

In [166]:
s.is_unique # for check the unique values

True

In [167]:
print(s.values)

[10 20 30 40 50]

In [168]:
print(s.keys())

RangeIndex(start=0, stop=5, step=1)

In [169]:
print(type(s.index))

<class 'pandas.core.indexes.range.RangeIndex'>

In [170]:
print(type(s.values))

<class 'numpy.ndarray'>

**Reading csv(comma seperted values) files with pandas**

In [171]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [172]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TopRichestInWorld.csv')
df

,Name,NetWorth,Age,Country/Territory,Source,Industry
0,Elon Musk,"$219,000,000,000",50,United States,"Tesla, SpaceX",Automotive
1,Jeff Bezos,"$171,000,000,000",58,United States,Amazon,Technology
2,Bernard Arnault & family,"$158,000,000,000",73,France,LVMH,Fashion & Retail
3,Bill Gates,"$129,000,000,000",66,United States,Microsoft,Technology
4,Warren Buffett,"$118,000,000,000",91,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...
96,Vladimir Potanin,"$17,300,000,000",61,Russia,metals,Metals & Mining
97,Harold Hamm & family,"$17,200,000,000",76,United States,oil & gas,Energy
98,Sun Piaoyang,"$17,100,000,000",63,China,pharmaceuticals,Healthcare
99,Luo Liguo & family,"$17,000,000,000",66,China,chemicals,Manufacturing
100,Peter Woo,"$17,000,000,000",75,Hong Kong,real estate,Real Estate

In [173]:
type(df)

pandas.core.frame.DataFrame

In [174]:
df.head()#it is used for fetch the values from top by default it fetch only top 5

,Name,NetWorth,Age,Country/Territory,Source,Industry
0,Elon Musk,"$219,000,000,000",50,United States,"Tesla, SpaceX",Automotive
1,Jeff Bezos,"$171,000,000,000",58,United States,Amazon,Technology
2,Bernard Arnault & family,"$158,000,000,000",73,France,LVMH,Fashion & Retail
3,Bill Gates,"$129,000,000,000",66,United States,Microsoft,Technology
4,Warren Buffett,"$118,000,000,000",91,United States,Berkshire Hathaway,Finance & Investments

In [175]:
df.head(10)

,Name,NetWorth,Age,Country/Territory,Source,Industry
0,Elon Musk,"$219,000,000,000",50,United States,"Tesla, SpaceX",Automotive
1,Jeff Bezos,"$171,000,000,000",58,United States,Amazon,Technology
2,Bernard Arnault & family,"$158,000,000,000",73,France,LVMH,Fashion & Retail
3,Bill Gates,"$129,000,000,000",66,United States,Microsoft,Technology
4,Warren Buffett,"$118,000,000,000",91,United States,Berkshire Hathaway,Finance & Investments
5,Larry Page,"$111,000,000,000",49,United States,Google,Technology
6,Sergey Brin,"$107,000,000,000",48,United States,Google,Technology
7,Larry Ellison,"$106,000,000,000",77,United States,software,Technology
8,Steve Ballmer,"$91,400,000,000",66,United States,Microsoft,Technology
9,Mukesh Ambani,"$90,700,000,000",64,India,diversified,Diversified

In [176]:
# how to read Series (usecols=[coloumn name waht you want ])

In [177]:
s=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/TopRichestInWorld.csv",usecols=["Name"])
s

                         Name
0                   Elon Musk
1                  Jeff Bezos
2    Bernard Arnault & family
3                  Bill Gates
4              Warren Buffett
..                        ...
96           Vladimir Potanin
97       Harold Hamm & family
98               Sun Piaoyang
99         Luo Liguo & family
100                 Peter Woo

[101 rows x 1 columns]

In [178]:
print(type(s))

<class 'pandas.core.frame.DataFrame'>

In [179]:
#now how to cnver data frame to Series we simplie used squeeze()
s=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/TopRichestInWorld.csv",usecols=["Name"]).squeeze()
s

0                     Elon Musk
1                    Jeff Bezos
2      Bernard Arnault & family
3                    Bill Gates
4                Warren Buffett
                 ...
96             Vladimir Potanin
97         Harold Hamm & family
98                 Sun Piaoyang
99           Luo Liguo & family
100                   Peter Woo
Name: Name, Length: 101, dtype: object

In [180]:
print(type(s))

<class 'pandas.core.series.Series'>

In [181]:
s.to_csv("richest.csv")# to save our file in seprated series

In [182]:
s.to_csv("richest.csv",index=False)

In [183]:
s1=pd.read_csv("richest.csv").squeeze()
print(s1)
print(type(s1))

0                     Elon Musk
1                    Jeff Bezos
2      Bernard Arnault & family
3                    Bill Gates
4                Warren Buffett
                 ...
96             Vladimir Potanin
97         Harold Hamm & family
98                 Sun Piaoyang
99           Luo Liguo & family
100                   Peter Woo
Name: Name, Length: 101, dtype: object
<class 'pandas.core.series.Series'>

In [184]:
s1.head()

0                   Elon Musk
1                  Jeff Bezos
2    Bernard Arnault & family
3                  Bill Gates
4              Warren Buffett
Name: Name, dtype: object

In [185]:
s1.head(3)

0                   Elon Musk
1                  Jeff Bezos
2    Bernard Arnault & family
Name: Name, dtype: object

In [186]:
s1.head(10)

0                   Elon Musk
1                  Jeff Bezos
2    Bernard Arnault & family
3                  Bill Gates
4              Warren Buffett
5                  Larry Page
6                 Sergey Brin
7               Larry Ellison
8               Steve Ballmer
9               Mukesh Ambani
Name: Name, dtype: object

In [187]:
s1.head(-10)#-10 10 record delete kar dega piche ke

0                    Elon Musk
1                   Jeff Bezos
2     Bernard Arnault & family
3                   Bill Gates
4               Warren Buffett
                ...
86              Vladimir Lisin
87        Fan Hongwei & family
88              Lakshmi Mittal
89              Andrew Forrest
90     Jiang Rensheng & family
Name: Name, Length: 91, dtype: object

In [188]:
s1.tail()#by default it shows last 5 record

96         Vladimir Potanin
97     Harold Hamm & family
98             Sun Piaoyang
99       Luo Liguo & family
100               Peter Woo
Name: Name, dtype: object

In [189]:
s1.tail(10)

91     Savitri Jindal & family
92                 Wang Wenyin
93                   Li Xiting
94              Stefan Persson
95                 Steve Cohen
96            Vladimir Potanin
97        Harold Hamm & family
98                Sun Piaoyang
99          Luo Liguo & family
100                  Peter Woo
Name: Name, dtype: object

In [190]:
s1.tail(-10)#first ke 10 record delete kar dega

10                     Gautam Adani & family
11                         Michael Bloomberg
12                 Carlos Slim Helu & family
13     Francoise Bettencourt Meyers & family
14                           Mark Zuckerberg
                       ...
96                          Vladimir Potanin
97                      Harold Hamm & family
98                              Sun Piaoyang
99                        Luo Liguo & family
100                                Peter Woo
Name: Name, Length: 91, dtype: object

### **sorting using sort_values functions**

In [191]:
s2=s1.sort_values(axis=0)#sort name wise
s2

74         Abigail Johnson
42        Alain Wertheimer
17            Alice Walton
22          Amancio Ortega
89          Andrew Forrest
              ...
4           Warren Buffett
54        William Lei Ding
85    Yang Huiyan & family
24            Zhang Yiming
16          Zhong Shanshan
Name: Name, Length: 101, dtype: object

In [192]:
s2=s1.sort_values(axis=0,ascending=False)
s2

16          Zhong Shanshan
24            Zhang Yiming
85    Yang Huiyan & family
54        William Lei Ding
4           Warren Buffett
              ...
89          Andrew Forrest
22          Amancio Ortega
17            Alice Walton
42        Alain Wertheimer
74         Abigail Johnson
Name: Name, Length: 101, dtype: object

In [193]:
#we also use kind foor specific sorting like quick merge
s2=s1.sort_values(axis=0,ascending=False,kind="quicksort")
s2

16          Zhong Shanshan
24            Zhang Yiming
85    Yang Huiyan & family
54        William Lei Ding
4           Warren Buffett
              ...
89          Andrew Forrest
22          Amancio Ortega
17            Alice Walton
42        Alain Wertheimer
74         Abigail Johnson
Name: Name, Length: 101, dtype: object

In [194]:
##meaning of in place
arr=[1,6,8,3,None,4,None,2,9]
s3=pd.Series(arr)
s3

0    1.0
1    6.0
2    8.0
3    3.0
4    NaN
5    4.0
6    NaN
7    2.0
8    9.0
dtype: float64

In [195]:
#sabhi nan value ok last me karne ke liye temprory
s3.sort_values(axis=0,na_position="last")# not in_place

0    1.0
7    2.0
3    3.0
5    4.0
1    6.0
2    8.0
8    9.0
4    NaN
6    NaN
dtype: float64

In [196]:
##in_place
s4=pd.Series(arr)
s4

0    1.0
1    6.0
2    8.0
3    3.0
4    NaN
5    4.0
6    NaN
7    2.0
8    9.0
dtype: float64

In [197]:
s4.sort_values(axis=0,na_position="last",inplace=True)
s4

0    1.0
7    2.0
3    3.0
5    4.0
1    6.0
2    8.0
8    9.0
4    NaN
6    NaN
dtype: float64

In [198]:
s3

0    1.0
1    6.0
2    8.0
3    3.0
4    NaN
5    4.0
6    NaN
7    2.0
8    9.0
dtype: float64

In [199]:
s4

0    1.0
7    2.0
3    3.0
5    4.0
1    6.0
2    8.0
8    9.0
4    NaN
6    NaN
dtype: float64

### **Value_counts**

In [200]:
#it works as group by command in sql

In [201]:
s6=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/TopRichestInWorld.csv",usecols=["Industry",]).squeeze()
s6

0                 Automotive
1                 Technology
2           Fashion & Retail
3                 Technology
4      Finance & Investments
               ...
96           Metals & Mining
97                    Energy
98                Healthcare
99             Manufacturing
100              Real Estate
Name: Industry, Length: 101, dtype: object

In [202]:
s6.value_counts()

Industry
Fashion & Retail         18
Technology               15
Finance & Investments    13
Metals & Mining           9
Food & Beverage           8
Automotive                7
Diversified               6
Manufacturing             5
Healthcare                5
Media & Entertainment     4
Real Estate               3
Telecom                   2
Logistics                 2
Energy                    2
Gambling & Casinos        1
Service                   1
Name: count, dtype: int64

In [203]:
"""normalize=True provide the normalization
means the contibution of the every makket
 between 0 to 1  the highst value is alway 1"""
s6.value_counts(normalize=True)

Industry
Fashion & Retail         0.178218
Technology               0.148515
Finance & Investments    0.128713
Metals & Mining          0.089109
Food & Beverage          0.079208
Automotive               0.069307
Diversified              0.059406
Manufacturing            0.049505
Healthcare               0.049505
Media & Entertainment    0.039604
Real Estate              0.029703
Telecom                  0.019802
Logistics                0.019802
Energy                   0.019802
Gambling & Casinos       0.009901
Service                  0.009901
Name: proportion, dtype: float64

In [204]:
s6.value_counts(normalize=True).sum()

np.float64(1.0)

In [205]:
df

,Name,NetWorth,Age,Country/Territory,Source,Industry
0,Elon Musk,"$219,000,000,000",50,United States,"Tesla, SpaceX",Automotive
1,Jeff Bezos,"$171,000,000,000",58,United States,Amazon,Technology
2,Bernard Arnault & family,"$158,000,000,000",73,France,LVMH,Fashion & Retail
3,Bill Gates,"$129,000,000,000",66,United States,Microsoft,Technology
4,Warren Buffett,"$118,000,000,000",91,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...
96,Vladimir Potanin,"$17,300,000,000",61,Russia,metals,Metals & Mining
97,Harold Hamm & family,"$17,200,000,000",76,United States,oil & gas,Energy
98,Sun Piaoyang,"$17,100,000,000",63,China,pharmaceuticals,Healthcare
99,Luo Liguo & family,"$17,000,000,000",66,China,chemicals,Manufacturing
100,Peter Woo,"$17,000,000,000",75,Hong Kong,real estate,Real Estate

**Use of indexing to fetch value**

In [209]:
s7=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/TopRichestInWorld.csv",usecols=["Name","NetWorth"],index_col="Name").squeeze()
s7

Name
Elon Musk                   $219,000,000,000
Jeff Bezos                  $171,000,000,000
Bernard Arnault & family    $158,000,000,000
Bill Gates                  $129,000,000,000
Warren Buffett              $118,000,000,000
                                  ...
Vladimir Potanin             $17,300,000,000
Harold Hamm & family         $17,200,000,000
Sun Piaoyang                 $17,100,000,000
Luo Liguo & family           $17,000,000,000
Peter Woo                    $17,000,000,000
Name: NetWorth, Length: 101, dtype: object

In [210]:
s7[0]

/tmp/ipykernel_1225/2459553882.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s7[0]

'$219,000,000,000'

In [212]:
s7[0:1]

Name
Elon Musk    $219,000,000,000
Name: NetWorth, dtype: object

In [215]:
s7[[-1]]

/tmp/ipykernel_1225/3920316464.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s7[[-1]]

Name
Peter Woo    $17,000,000,000
Name: NetWorth, dtype: object

In [214]:
s7[[0,1,2,3]]

/tmp/ipykernel_1225/2727603924.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s7[[0,1,2,3]]

Name
Elon Musk                   $219,000,000,000
Jeff Bezos                  $171,000,000,000
Bernard Arnault & family    $158,000,000,000
Bill Gates                  $129,000,000,000
Name: NetWorth, dtype: object