In [474]:
import numpy as np
import pandas as pd

In [475]:
d={"A":10,"B":20,"C":30.2,"D":40.1}
s=pd.Series(d)
s

A    10.0
B    20.0
C    30.2
D    40.1
dtype: float64

In [476]:
s.sum()

np.float64(100.30000000000001)

In [477]:
s.prod()

np.float64(242204.0)

In [478]:
s.mean()

np.float64(25.075000000000003)

In [479]:
s.median()

25.1

In [480]:
s.std()

12.974686894102685

In [481]:
s.max()

40.1

In [482]:
s.min()

10.0

In [483]:
s.argmax()

np.int64(3)

In [484]:
s.argmin()

np.int64(0)

In [485]:
s.idxmax()

'D'

In [486]:
s.idxmin()

'A'

In [487]:
s.isnull()

A    False
B    False
C    False
D    False
dtype: bool

In [488]:
s.hasnans

False

In [489]:
s.is_unique

True

In [490]:
s.dtype

dtype('float64')

In [491]:
type(s)

pandas.core.series.Series

In [492]:
s.size

4

In [493]:
s.shape

(4,)

In [494]:
s.ndim

1

# **DataFrame**

In [495]:
d={"name":["Abhay","Mihika","Deepa"],"age":[20,21,22],"city":["Bhopal","Satna","Bhopal"]}

In [496]:
df=pd.DataFrame(d)
df

     name  age    city
0   Abhay   20  Bhopal
1  Mihika   21   Satna
2   Deepa   22  Bhopal

In [497]:
df["name"]

0     Abhay
1    Mihika
2     Deepa
Name: name, dtype: object

In [498]:
type(df["name"])

pandas.core.series.Series

 **Series VS DataFrame**

In [499]:
d={"a":10,"b":20,"c":30}
s=pd.Series(d)
s

a    10
b    20
c    30
dtype: int64

In [500]:
d={"a":[10,20,30],"b":[40,50,60],"c":[70,80,90]}
df=pd.DataFrame(d)
df

    a   b   c
0  10  40  70
1  20  50  80
2  30  60  90

In [501]:
df.sum() #for every column sum by difault

a     60
b    150
c    240
dtype: int64

In [502]:
df.sum(axis=1)#for every row

0    120
1    150
2    180
dtype: int64

In [503]:
df.sum(axis=0)#for column

a     60
b    150
c    240
dtype: int64

In [504]:
# if you want to know the whole sum
df.sum().sum()

np.int64(450)

In [505]:
df

    a   b   c
0  10  40  70
1  20  50  80
2  30  60  90

In [506]:
df.min() #by difault min value column wise

a    10
b    40
c    70
dtype: int64

In [507]:
df.max()#every column by difault

a    30
b    60
c    90
dtype: int64

In [508]:
df.min(axis=1)#row wise

0    10
1    20
2    30
dtype: int64

In [509]:
df.max(axis=1)#row wise

0    70
1    80
2    90
dtype: int64

In [510]:
df.prod()

a      6000
b    120000
c    504000
dtype: int64

In [511]:
df.prod(axis=1)

0     28000
1     80000
2    162000
dtype: int64

**IN Pandas axis=1 row and axis=0 column but numb py oposite**

In [512]:
df.idxmax()

a    2
b    2
c    2
dtype: int64

In [513]:
df.idxmin()

a    0
b    0
c    0
dtype: int64

In [514]:
df.std()

a    10.0
b    10.0
c    10.0
dtype: float64

In [515]:
df.mean()

a    20.0
b    50.0
c    80.0
dtype: float64

In [516]:
df.isnull()

       a      b      c
0  False  False  False
1  False  False  False
2  False  False  False

**wroking on imdb dataset**

In [517]:
#df=pd.read_csv('/Content/drive/MyDrive/Colab Notebooks/imdb1000.csv')
df=pd.read_csv ("/content/imdb1000.csv",usecols=["Series_Title","IMDB_Rating","No_of_Votes","Gross"])
df

                 Series_Title  IMDB_Rating  No_of_Votes        Gross
0    The Shawshank Redemption          9.3      2343110   28,341,469
1               The Godfather          9.2      1620367  134,966,411
2             The Dark Knight          9.0      2303232  534,858,444
3      The Godfather: Part II          9.0      1129952   57,300,000
4                12 Angry Men          9.0       689845    4,360,000
..                        ...          ...          ...          ...
995    Breakfast at Tiffany's          7.6       166544          NaN
996                     Giant          7.6        34075          NaN
997     From Here to Eternity          7.6        43374   30,500,000
998                  Lifeboat          7.6        26471          NaN
999              The 39 Steps          7.6        51853          NaN

[1000 rows x 4 columns]

In [518]:
df

                 Series_Title  IMDB_Rating  No_of_Votes        Gross
0    The Shawshank Redemption          9.3      2343110   28,341,469
1               The Godfather          9.2      1620367  134,966,411
2             The Dark Knight          9.0      2303232  534,858,444
3      The Godfather: Part II          9.0      1129952   57,300,000
4                12 Angry Men          9.0       689845    4,360,000
..                        ...          ...          ...          ...
995    Breakfast at Tiffany's          7.6       166544          NaN
996                     Giant          7.6        34075          NaN
997     From Here to Eternity          7.6        43374   30,500,000
998                  Lifeboat          7.6        26471          NaN
999              The 39 Steps          7.6        51853          NaN

[1000 rows x 4 columns]

In [519]:
df.head()

               Series_Title  IMDB_Rating  No_of_Votes        Gross
0  The Shawshank Redemption          9.3      2343110   28,341,469
1             The Godfather          9.2      1620367  134,966,411
2           The Dark Knight          9.0      2303232  534,858,444
3    The Godfather: Part II          9.0      1129952   57,300,000
4              12 Angry Men          9.0       689845    4,360,000

In [520]:
df.tail()

               Series_Title  IMDB_Rating  No_of_Votes       Gross
995  Breakfast at Tiffany's          7.6       166544         NaN
996                   Giant          7.6        34075         NaN
997   From Here to Eternity          7.6        43374  30,500,000
998                Lifeboat          7.6        26471         NaN
999            The 39 Steps          7.6        51853         NaN

In [521]:
df.tail(-990)

               Series_Title  IMDB_Rating  No_of_Votes        Gross
990            Giù la testa          7.6        30144      696,690
991          Kelly's Heroes          7.6        45338    1,378,435
992         The Jungle Book          7.6       166409  141,843,612
993                  Blowup          7.6        56513          NaN
994      A Hard Day's Night          7.6        40351   13,780,024
995  Breakfast at Tiffany's          7.6       166544          NaN
996                   Giant          7.6        34075          NaN
997   From Here to Eternity          7.6        43374   30,500,000
998                Lifeboat          7.6        26471          NaN
999            The 39 Steps          7.6        51853          NaN

In [522]:
df.head(-990)

,Series_Title,IMDB_Rating,No_of_Votes,Gross
0,The Shawshank Redemption,9.3,2343110,"28,341,469"
1,The Godfather,9.2,1620367,"134,966,411"
2,The Dark Knight,9.0,2303232,"534,858,444"
3,The Godfather: Part II,9.0,1129952,"57,300,000"
4,12 Angry Men,9.0,689845,"4,360,000"
5,The Lord of the Rings: The Return of the King,8.9,1642758,"377,845,905"
6,Pulp Fiction,8.9,1826188,"107,928,762"
7,Schindler's List,8.9,1213505,"96,898,818"
8,Inception,8.8,2067042,"292,576,195"
9,Fight Club,8.8,1854740,"37,030,102"

**df.describe() provides the states summary of the data frame like count , mean,std,min etc**

In [523]:
df.describe().round(2)

       IMDB_Rating  No_of_Votes
count      1000.00      1000.00
mean          7.95    273692.91
std           0.28    327372.70
min           7.60     25088.00
25%           7.70     55526.25
50%           7.90    138548.50
75%           8.10    374161.25
max           9.30   2343110.00

In [524]:
df.dtypes

Series_Title     object
IMDB_Rating     float64
No_of_Votes       int64
Gross            object
dtype: object

In [525]:
#here we also want decribe add gross but it is a comma
#spreate so firstly we replace commna to empty string
#after that we convert it inot int
df["Gross"]=df["Gross"].str.replace(",","")
df

                 Series_Title  IMDB_Rating  No_of_Votes      Gross
0    The Shawshank Redemption          9.3      2343110   28341469
1               The Godfather          9.2      1620367  134966411
2             The Dark Knight          9.0      2303232  534858444
3      The Godfather: Part II          9.0      1129952   57300000
4                12 Angry Men          9.0       689845    4360000
..                        ...          ...          ...        ...
995    Breakfast at Tiffany's          7.6       166544        NaN
996                     Giant          7.6        34075        NaN
997     From Here to Eternity          7.6        43374   30500000
998                  Lifeboat          7.6        26471        NaN
999              The 39 Steps          7.6        51853        NaN

[1000 rows x 4 columns]

In [526]:
#before converting to int we fill the nan value so
#we use fillna()
df["Gross"]=df["Gross"].fillna(0)
df

                 Series_Title  IMDB_Rating  No_of_Votes      Gross
0    The Shawshank Redemption          9.3      2343110   28341469
1               The Godfather          9.2      1620367  134966411
2             The Dark Knight          9.0      2303232  534858444
3      The Godfather: Part II          9.0      1129952   57300000
4                12 Angry Men          9.0       689845    4360000
..                        ...          ...          ...        ...
995    Breakfast at Tiffany's          7.6       166544          0
996                     Giant          7.6        34075          0
997     From Here to Eternity          7.6        43374   30500000
998                  Lifeboat          7.6        26471          0
999              The 39 Steps          7.6        51853          0

[1000 rows x 4 columns]

In [527]:
#now we convert it so use astype
df["Gross"]=df["Gross"].astype("int64")
df.dtypes

Series_Title     object
IMDB_Rating     float64
No_of_Votes       int64
Gross             int64
dtype: object

In [528]:
#now check is decribe consider it
df.describe().round(2)

       IMDB_Rating  No_of_Votes         Gross
count      1000.00      1000.00  1.000000e+03
mean          7.95    273692.91  5.653688e+07
std           0.28    327372.70  1.032382e+08
min           7.60     25088.00  0.000000e+00
25%           7.70     55526.25  4.457098e+05
50%           7.90    138548.50  1.070275e+07
75%           8.10    374161.25  6.153989e+07
max           9.30   2343110.00  9.366622e+08

In [529]:
#df.info()used for give the structure sumarry of the df like non value d type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Series_Title  1000 non-null   object
 1   IMDB_Rating   1000 non-null   float64
 2   No_of_Votes   1000 non-null   int64
 3   Gross         1000 non-null   int64
dtypes: float64(1), int64(2), object(1)
memory usage: 31.4+ KB

**n largest**

In [530]:
df=pd.read_csv("/content/imdb1000.csv",usecols=["Series_Title","IMDB_Rating","No_of_Votes"])
df

                 Series_Title  IMDB_Rating  No_of_Votes
0    The Shawshank Redemption          9.3      2343110
1               The Godfather          9.2      1620367
2             The Dark Knight          9.0      2303232
3      The Godfather: Part II          9.0      1129952
4                12 Angry Men          9.0       689845
..                        ...          ...          ...
995    Breakfast at Tiffany's          7.6       166544
996                     Giant          7.6        34075
997     From Here to Eternity          7.6        43374
998                  Lifeboat          7.6        26471
999              The 39 Steps          7.6        51853

[1000 rows x 3 columns]

In [531]:
#nlargest() in pandas returns the top n rows
# with the highest values from a specified column.

In [532]:
df.nlargest(10,columns="IMDB_Rating")

                                    Series_Title  IMDB_Rating  No_of_Votes
0                       The Shawshank Redemption          9.3      2343110
1                                  The Godfather          9.2      1620367
2                                The Dark Knight          9.0      2303232
3                         The Godfather: Part II          9.0      1129952
4                                   12 Angry Men          9.0       689845
5  The Lord of the Rings: The Return of the King          8.9      1642758
6                                   Pulp Fiction          8.9      1826188
7                               Schindler's List          8.9      1213505
8                                      Inception          8.8      2067042
9                                     Fight Club          8.8      1854740

In [533]:
df.nlargest(10,columns=["No_of_Votes"])

,Series_Title,IMDB_Rating,No_of_Votes
0,The Shawshank Redemption,9.3,2343110
2,The Dark Knight,9.0,2303232
8,Inception,8.8,2067042
9,Fight Club,8.8,1854740
6,Pulp Fiction,8.9,1826188
11,Forrest Gump,8.8,1809221
14,The Matrix,8.7,1676426
10,The Lord of the Rings: The Fellowship of the Ring,8.8,1661481
5,The Lord of the Rings: The Return of the King,8.9,1642758
1,The Godfather,9.2,1620367

In [534]:
df.nlargest(10,columns=["No_of_Votes","IMDB_Rating"])

,Series_Title,IMDB_Rating,No_of_Votes
0,The Shawshank Redemption,9.3,2343110
2,The Dark Knight,9.0,2303232
8,Inception,8.8,2067042
9,Fight Club,8.8,1854740
6,Pulp Fiction,8.9,1826188
11,Forrest Gump,8.8,1809221
14,The Matrix,8.7,1676426
10,The Lord of the Rings: The Fellowship of the Ring,8.8,1661481
5,The Lord of the Rings: The Return of the King,8.9,1642758
1,The Godfather,9.2,1620367

In [535]:
#df.nsmallest() in pandas returns the top n rows
#with the smallest values from a specified column.

In [536]:
df.nsmallest(10,columns="IMDB_Rating")

                         Series_Title  IMDB_Rating  No_of_Votes
877                       Dark Waters          7.6        60408
878                         Searching          7.6       140840
879  Once Upon a Time... in Hollywood          7.6       551309
880                          Nelyubov          7.6        29765
881               The Florida Project          7.6        95181
882                        Just Mercy          7.6        46739
883                            Gifted          7.6        99643
884          The Peanut Butter Falcon          7.6        66346
885                          Victoria          7.6        52903
886                           Mustang          7.6        35785

**How to make coloum as index we use set_index**

In [537]:
df.set_index("Series_Title")

                          IMDB_Rating  No_of_Votes
Series_Title
The Shawshank Redemption          9.3      2343110
The Godfather                     9.2      1620367
The Dark Knight                   9.0      2303232
The Godfather: Part II            9.0      1129952
12 Angry Men                      9.0       689845
...                               ...          ...
Breakfast at Tiffany's            7.6       166544
Giant                             7.6        34075
From Here to Eternity             7.6        43374
Lifeboat                          7.6        26471
The 39 Steps                      7.6        51853

[1000 rows x 2 columns]

In [538]:
df

                 Series_Title  IMDB_Rating  No_of_Votes
0    The Shawshank Redemption          9.3      2343110
1               The Godfather          9.2      1620367
2             The Dark Knight          9.0      2303232
3      The Godfather: Part II          9.0      1129952
4                12 Angry Men          9.0       689845
..                        ...          ...          ...
995    Breakfast at Tiffany's          7.6       166544
996                     Giant          7.6        34075
997     From Here to Eternity          7.6        43374
998                  Lifeboat          7.6        26471
999              The 39 Steps          7.6        51853

[1000 rows x 3 columns]

In [539]:
#by default it give viwe to copy we you want
#parmament change use inplace=True
df.set_index("Series_Title",inplace=True)
df

                          IMDB_Rating  No_of_Votes
Series_Title
The Shawshank Redemption          9.3      2343110
The Godfather                     9.2      1620367
The Dark Knight                   9.0      2303232
The Godfather: Part II            9.0      1129952
12 Angry Men                      9.0       689845
...                               ...          ...
Breakfast at Tiffany's            7.6       166544
Giant                             7.6        34075
From Here to Eternity             7.6        43374
Lifeboat                          7.6        26471
The 39 Steps                      7.6        51853

[1000 rows x 2 columns]

In [540]:
#to reset index use reset_index
df.reset_index(inplace=True)
df

                 Series_Title  IMDB_Rating  No_of_Votes
0    The Shawshank Redemption          9.3      2343110
1               The Godfather          9.2      1620367
2             The Dark Knight          9.0      2303232
3      The Godfather: Part II          9.0      1129952
4                12 Angry Men          9.0       689845
..                        ...          ...          ...
995    Breakfast at Tiffany's          7.6       166544
996                     Giant          7.6        34075
997     From Here to Eternity          7.6        43374
998                  Lifeboat          7.6        26471
999              The 39 Steps          7.6        51853

[1000 rows x 3 columns]

**drop method to delete any specific coloum**

In [541]:
df.drop(columns=["Series_Title"],inplace=True)
df

     IMDB_Rating  No_of_Votes
0            9.3      2343110
1            9.2      1620367
2            9.0      2303232
3            9.0      1129952
4            9.0       689845
..           ...          ...
995          7.6       166544
996          7.6        34075
997          7.6        43374
998          7.6        26471
999          7.6        51853

[1000 rows x 2 columns]

In [542]:
#we also drop the labels like rows
df.drop(labels=[2,3,4],inplace=True)
df

     IMDB_Rating  No_of_Votes
0            9.3      2343110
1            9.2      1620367
5            8.9      1642758
6            8.9      1826188
7            8.9      1213505
..           ...          ...
995          7.6       166544
996          7.6        34075
997          7.6        43374
998          7.6        26471
999          7.6        51853

[997 rows x 2 columns]

In [543]:
df=pd.read_csv("/content/imdb1000.csv",usecols=["Series_Title","IMDB_Rating","No_of_Votes"])
df

                 Series_Title  IMDB_Rating  No_of_Votes
0    The Shawshank Redemption          9.3      2343110
1               The Godfather          9.2      1620367
2             The Dark Knight          9.0      2303232
3      The Godfather: Part II          9.0      1129952
4                12 Angry Men          9.0       689845
..                        ...          ...          ...
995    Breakfast at Tiffany's          7.6       166544
996                     Giant          7.6        34075
997     From Here to Eternity          7.6        43374
998                  Lifeboat          7.6        26471
999              The 39 Steps          7.6        51853

[1000 rows x 3 columns]

## **01/04/26**

In [544]:
import numpy as np
import pandas as pd

In [545]:
d={"India":"Jalebi","Aus":"Kang","Us":"Pizza"}
pd.Series(d)

India    Jalebi
Aus        Kang
Us        Pizza
dtype: object

In [546]:
d={"name":["Abhay","Deepanjali","Aryan","Akansha"],"Age":[21,20,21,20],"Marks":[8,9,8,10]}
df=pd.DataFrame(d)
df

         name  Age  Marks
0       Abhay   21      8
1  Deepanjali   20      9
2       Aryan   21      8
3     Akansha   20     10

In [547]:
df.sum()

name     AbhayDeepanjaliAryanAkansha
Age                               82
Marks                             35
dtype: object

In [548]:
df.max()

name     Deepanjali
Age              21
Marks            10
dtype: object

In [549]:
df.min()

name     Abhay
Age         20
Marks        8
dtype: object

In [550]:
df.idxmax()

name     1
Age      0
Marks    3
dtype: int64

In [551]:
df.idxmin()

name     0
Age      1
Marks    0
dtype: int64

In [552]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   Age     4 non-null      int64
 2   Marks   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [553]:
df.describe()

            Age      Marks
count   4.00000   4.000000
mean   20.50000   8.750000
std     0.57735   0.957427
min    20.00000   8.000000
25%    20.00000   8.000000
50%    20.50000   8.500000
75%    21.00000   9.250000
max    21.00000  10.000000

In [554]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [555]:
df.columns

Index(['name', 'Age', 'Marks'], dtype='object')

In [556]:
df.size

12

In [557]:
df.isnull()

    name    Age  Marks
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [558]:
df["Age"]

0    21
1    20
2    21
3    20
Name: Age, dtype: int64

In [559]:
df["name"]

0         Abhay
1    Deepanjali
2         Aryan
3       Akansha
Name: name, dtype: object

In [560]:
df["Marks"]

0     8
1     9
2     8
3    10
Name: Marks, dtype: int64

**how to read excel file(.xls-old file ,.xlsx-new file)**

In [561]:
import xlrd #for read old excel file

In [562]:
df=pd.read_excel("/content/titanic.xls")
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

**loc(it is realted to labels) vs iloc(it is realte to index )**

In [563]:
df.iloc[2]

pclass                                     1
survived                                   0
name            Allison, Miss. Helen Loraine
sex                                   female
age                                      2.0
sibsp                                      1
parch                                      2
ticket                                113781
fare                                  151.55
cabin                                C22 C26
embarked                                   S
boat                                     NaN
body                                     NaN
home.dest    Montreal, PQ / Chesterville, ON
Name: 2, dtype: object

In [564]:
df.iloc[[2,4]]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
2,1,0,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.55,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.55,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [565]:
df.iloc[[2,4,6,8]]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
2,1,0,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"

In [566]:
df.loc[[2,4,6,8]]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
2,1,0,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"

In [567]:
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

**iloc fully wrok with integers in rows it also 0 1 to n index and column also 0 ,1 to n index**

In [568]:
df.iloc[[1,3,5],[0,1,2,3,4]]

   pclass  survived                                  name   sex      age
1       1         1        Allison, Master. Hudson Trevor  male   0.9167
3       1         0  Allison, Mr. Hudson Joshua Creighton  male  30.0000
5       1         1                   Anderson, Mr. Harry  male  48.0000

**loc not fully wokr with int if you want any specific column you should write the column name no number as iloc**

In [569]:
df.loc[[2,4,5,6],["name","survived","sex"]]

                                              name  survived     sex
2                     Allison, Miss. Helen Loraine         0  female
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)         0  female
5                              Anderson, Mr. Harry         1    male
6                Andrews, Miss. Kornelia Theodosia         1  female

In [570]:
df.set_index('name',inplace=True)
df

,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
name,,,,,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
"Allison, Master. Hudson Trevor",1,1,male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Miss. Helen Loraine",1,0,female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
"Zabour, Miss. Thamine",3,0,female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
"Zakarian, Mr. Ortin",3,0,male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
"Zimmerman, Mr. Leo",3,0,male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [571]:
df.loc["Allen, Miss. Elisabeth Walton"]

pclass                  1
survived                1
sex                female
age                  29.0
sibsp                   0
parch                   0
ticket              24160
fare             211.3375
cabin                  B5
embarked                S
boat                    2
body                  NaN
home.dest    St Louis, MO
Name: Allen, Miss. Elisabeth Walton, dtype: object

In [572]:
df.iloc[0]

pclass                  1
survived                1
sex                female
age                  29.0
sibsp                   0
parch                   0
ticket              24160
fare             211.3375
cabin                  B5
embarked                S
boat                    2
body                  NaN
home.dest    St Louis, MO
Name: Allen, Miss. Elisabeth Walton, dtype: object

In [573]:
df.iloc[0:7]#we also performed slicing in iloc

,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
name,,,,,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
"Allison, Master. Hudson Trevor",1,1,male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Miss. Helen Loraine",1,0,female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
"Anderson, Mr. Harry",1,1,male,48.0000,0,0,19952,26.5500,E12,S,3,NaN,"New York, NY"
"Andrews, Miss. Kornelia Theodosia",1,1,female,63.0000,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"

### **Broadcasting**

In [574]:
s1=pd.Series([10,20,30])
s2=pd.Series([40,50,60])
s3=pd.Series([70,80,90,100,110,120])

In [575]:
s1+s2

0    50
1    70
2    90
dtype: int64

In [576]:
#nan ke sath + ya _ always nan hota hai
s1+s3

0     80.0
1    100.0
2    120.0
3      NaN
4      NaN
5      NaN
dtype: float64

In [577]:
s1+s2

0    50
1    70
2    90
dtype: int64

**Broadcasting in DataFrame**

In [578]:
d1={"name":["a","b","c"],"marks1":[10,8,7],"marks2":[2,5,8]}
df1=pd.DataFrame(d1)
df1

  name  marks1  marks2
0    a      10       2
1    b       8       5
2    c       7       8

In [579]:
d2={"name":["s","k","d"],"marks1":[9,7,6],"marks2":[4,7,10]}
df2=pd.DataFrame(d2)
df2

  name  marks1  marks2
0    s       9       4
1    k       7       7
2    d       6      10

In [580]:
df1+df2

  name  marks1  marks2
0   as      19       6
1   bk      15      12
2   cd      13      18

In [581]:
d3={"age":[10,20,30,40],"marks1":[4,5,6,9],"marks2":[7,8,9,7],"city":["Bhopal","Indore","a","dffsdfs"]}
df3=pd.DataFrame(d3)
df3

   age  marks1  marks2     city
0   10       4       7   Bhopal
1   20       5       8   Indore
2   30       6       9        a
3   40       9       7  dffsdfs

In [582]:
df1+df3

   age  city  marks1  marks2  name
0  NaN   NaN    14.0     9.0   NaN
1  NaN   NaN    13.0    13.0   NaN
2  NaN   NaN    13.0    17.0   NaN
3  NaN   NaN     NaN     NaN   NaN

### **filtering**

In [583]:
df=pd.read_excel("/content/titanic.xls",usecols=["pclass","survived","name","fare","sex","age"])
df

,pclass,survived,name,sex,age,fare
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,211.3375
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,151.5500
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,151.5500
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,151.5500
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,151.5500
...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,14.4542
1305,3,0,"Zabour, Miss. Thamine",female,NaN,14.4542
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,7.2250
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,7.2250
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,7.8750

In [588]:

df

,pclass,survived,sex,age,fare
name,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,211.3375
"Allison, Master. Hudson Trevor",1,1,male,0.9167,151.5500
"Allison, Miss. Helen Loraine",1,0,female,2.0000,151.5500
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,151.5500
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,151.5500
...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,14.4542
"Zabour, Miss. Thamine",3,0,female,NaN,14.4542
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,7.2250
"Zakarian, Mr. Ortin",3,0,male,27.0000,7.2250
"Zimmerman, Mr. Leo",3,0,male,29.0000,7.8750

In [589]:
df.iloc[2]

pclass           1
survived         0
sex         female
age            2.0
fare        151.55
Name: Allison, Miss. Helen Loraine, dtype: object

In [590]:
#print all the males
#using boolean variable
males_df=df[df["sex"]=="male"]
males_df

,pclass,survived,sex,age,fare
name,,,,,
"Allison, Master. Hudson Trevor",1,1,male,0.9167,151.5500
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,151.5500
"Anderson, Mr. Harry",1,1,male,48.0000,26.5500
"Andrews, Mr. Thomas Jr",1,0,male,39.0000,0.0000
"Artagaveytia, Mr. Ramon",1,0,male,71.0000,49.5042
...,...,...,...,...,...
"Yousif, Mr. Wazli",3,0,male,NaN,7.2250
"Yousseff, Mr. Gerious",3,0,male,NaN,14.4583
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,7.2250
"Zakarian, Mr. Ortin",3,0,male,27.0000,7.2250
"Zimmerman, Mr. Leo",3,0,male,29.0000,7.8750

In [592]:
females_df=df[df["sex"]=="female"]
females_df

,pclass,survived,sex,age,fare
name,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0,211.3375
"Allison, Miss. Helen Loraine",1,0,female,2.0,151.5500
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0,151.5500
"Andrews, Miss. Kornelia Theodosia",1,1,female,63.0,77.9583
"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,1,female,53.0,51.4792
...,...,...,...,...,...
"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",3,1,female,38.0,7.2292
"Wilkes, Mrs. James (Ellen Needs)",3,1,female,47.0,7.0000
"Yasbeck, Mrs. Antoni (Selini Alexander)",3,1,female,15.0,14.4542
"Zabour, Miss. Hileni",3,0,female,14.5,14.4542
"Zabour, Miss. Thamine",3,0,female,NaN,14.4542

In [593]:
rich_kids_df=df[(df["age"]<20) & (df["fare"]>200)]
rich_kids_df

,pclass,survived,sex,age,fare
name,,,,,
"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",1,1,female,18.0,227.5250
"Fortune, Mr. Charles Alexander",1,0,male,19.0,263.0000
"Madill, Miss. Georgette Alexandra",1,1,female,15.0,211.3375
"Ryerson, Master. John Borie",1,1,male,13.0,262.3750
"Ryerson, Miss. Emily Borie",1,1,female,18.0,262.3750

In [595]:
poor_kids_df=df[(df["age"]<20)&(df["fare"]<20)]
poor_kids_df

,pclass,survived,sex,age,fare
name,,,,,
"Andrew, Mr. Edgardo Samuel",2,0,male,18.0,11.5000
"Bailey, Mr. Percy Andrew",2,0,male,18.0,11.5000
"Bentham, Miss. Lilian W",2,1,female,19.0,13.0000
"Carbines, Mr. William",2,0,male,19.0,13.0000
"Fahlstrom, Mr. Arne Jonas",2,0,male,18.0,13.0000
...,...,...,...,...,...
"Vander Planke, Mr. Leo Edmondus",3,0,male,16.0,18.0000
"Vestrom, Miss. Hulda Amanda Adolfina",3,0,female,14.0,7.8542
"Wiklund, Mr. Jakob Alfred",3,0,male,18.0,6.4958
"Yasbeck, Mrs. Antoni (Selini Alexander)",3,1,female,15.0,14.4542
"Zabour, Miss. Hileni",3,0,female,14.5,14.4542

In [596]:
old_age_df=df[(df["age"]>60) & (df["fare"]>200)]
old_age_df

,pclass,survived,sex,age,fare
name,,,,,
"Fortune, Mr. Mark",1,0,male,64.0,263.0000
"Ryerson, Mr. Arthur Larned",1,0,male,61.0,262.3750
"Straus, Mr. Isidor",1,0,male,67.0,221.7792
"Straus, Mrs. Isidor (Rosalie Ida Blun)",1,0,female,63.0,221.7792

In [598]:
old_age_df=df[(df["age"]>60) & (df["pclass"]==3)]
old_age_df

                           pclass  survived     sex   age    fare
name
Connors, Mr. Patrick            3         0    male  70.5  7.7500
Duane, Mr. Frank                3         0    male  65.0  7.7500
Nysveen, Mr. Johan Hansen       3         0    male  61.0  6.2375
Storey, Mr. Thomas              3         0    male  60.5     NaN
Svensson, Mr. Johan             3         0    male  74.0  7.7750
Turkula, Mrs. (Hedwig)          3         1  female  63.0  9.5875

In [599]:
rich_p=df[(df["pclass"]==1)]
rich_p

,pclass,survived,sex,age,fare
name,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,211.3375
"Allison, Master. Hudson Trevor",1,1,male,0.9167,151.5500
"Allison, Miss. Helen Loraine",1,0,female,2.0000,151.5500
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,151.5500
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,151.5500
...,...,...,...,...,...
"Williams-Lambert, Mr. Fletcher Fellows",1,0,male,NaN,35.0000
"Wilson, Miss. Helen Alice",1,1,female,31.0000,134.5000
"Woolner, Mr. Hugh",1,1,male,NaN,35.5000
"Wright, Mr. George",1,0,male,62.0000,26.5500
"Young, Miss. Marie Grice",1,1,female,36.0000,135.6333

**isnull(it is used to check the nan value in data set)**

In [603]:
no_age=df[df["age"].isnull()]
no_age

,pclass,survived,sex,age,fare
name,,,,,
"Baumann, Mr. John D",1,0,male,NaN,25.9250
"Bradley, Mr. George (""George Arthur Brayton"")",1,1,male,NaN,26.5500
"Brewe, Dr. Arthur Jackson",1,0,male,NaN,39.6000
"Cairns, Mr. Alexander",1,0,male,NaN,31.0000
"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)",1,1,female,NaN,27.7208
...,...,...,...,...,...
"Williams, Mr. Howard Hugh ""Harry""",3,0,male,NaN,8.0500
"Wiseman, Mr. Phillippe",3,0,male,NaN,7.2500
"Yousif, Mr. Wazli",3,0,male,NaN,7.2250
"Yousseff, Mr. Gerious",3,0,male,NaN,14.4583
"Zabour, Miss. Thamine",3,0,female,NaN,14.4542

In [604]:
no_gender=df[df["sex"].isnull()]
no_gender

Empty DataFrame
Columns: [pclass, survived, sex, age, fare]
Index: []

**rename(it is used to change the column name )**

In [606]:
df.rename(columns={"sex":"gender"},inplace=True)
df

,pclass,survived,gender,age,fare
name,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,211.3375
"Allison, Master. Hudson Trevor",1,1,male,0.9167,151.5500
"Allison, Miss. Helen Loraine",1,0,female,2.0000,151.5500
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,151.5500
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,151.5500
...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,14.4542
"Zabour, Miss. Thamine",3,0,female,NaN,14.4542
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,7.2250
"Zakarian, Mr. Ortin",3,0,male,27.0000,7.2250
"Zimmerman, Mr. Leo",3,0,male,29.0000,7.8750

In [608]:
df.rename(columns={"pclass":"class"})

,class,survived,gender,age,fare
name,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,211.3375
"Allison, Master. Hudson Trevor",1,1,male,0.9167,151.5500
"Allison, Miss. Helen Loraine",1,0,female,2.0000,151.5500
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,151.5500
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,151.5500
...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,14.4542
"Zabour, Miss. Thamine",3,0,female,NaN,14.4542
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,7.2250
"Zakarian, Mr. Ortin",3,0,male,27.0000,7.2250
"Zimmerman, Mr. Leo",3,0,male,29.0000,7.8750

### **map()**

In [609]:
df["survived"]=df["survived"].map({0:"dead",1:"alive"})
df

,pclass,survived,gender,age,fare
name,,,,,
"Allen, Miss. Elisabeth Walton",1,alive,female,29.0000,211.3375
"Allison, Master. Hudson Trevor",1,alive,male,0.9167,151.5500
"Allison, Miss. Helen Loraine",1,dead,female,2.0000,151.5500
"Allison, Mr. Hudson Joshua Creighton",1,dead,male,30.0000,151.5500
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,dead,female,25.0000,151.5500
...,...,...,...,...,...
"Zabour, Miss. Hileni",3,dead,female,14.5000,14.4542
"Zabour, Miss. Thamine",3,dead,female,NaN,14.4542
"Zakarian, Mr. Mapriededer",3,dead,male,26.5000,7.2250
"Zakarian, Mr. Ortin",3,dead,male,27.0000,7.2250
"Zimmerman, Mr. Leo",3,dead,male,29.0000,7.8750

In [610]:
df["survived"]=df["survived"].map({"dead":0,"alive":1})
df

,pclass,survived,gender,age,fare
name,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,211.3375
"Allison, Master. Hudson Trevor",1,1,male,0.9167,151.5500
"Allison, Miss. Helen Loraine",1,0,female,2.0000,151.5500
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,151.5500
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,151.5500
...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,14.4542
"Zabour, Miss. Thamine",3,0,female,NaN,14.4542
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,7.2250
"Zakarian, Mr. Ortin",3,0,male,27.0000,7.2250
"Zimmerman, Mr. Leo",3,0,male,29.0000,7.8750