# **14/04/2026**

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/Pokemon.csv")

In [3]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [5]:
df.describe().round(1)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.0,800.0,800.0,800.0,800.0,800.0,800.0,800.0,800.0
mean,362.8,435.1,69.3,79.0,73.8,72.8,71.9,68.3,3.3
std,208.3,120.0,25.5,32.5,31.2,32.7,27.8,29.1,1.7
min,1.0,180.0,1.0,5.0,5.0,10.0,20.0,5.0,1.0
25%,184.8,330.0,50.0,55.0,50.0,49.8,50.0,45.0,2.0
50%,364.5,450.0,65.0,75.0,70.0,65.0,70.0,65.0,3.0
75%,539.2,515.0,80.0,100.0,90.0,95.0,90.0,90.0,5.0
max,721.0,780.0,255.0,190.0,230.0,194.0,230.0,180.0,6.0

**apply() it is used to apply any specific funtion in dataset or changes in a single table**

In [6]:
df["name_length"]=df["Name"].apply(len)

In [7]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,name_length
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,9
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,7
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,8
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,21
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,7
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,19
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,19
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,18
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,9

In [8]:
df.drop(columns=["name_length"],inplace=True)

In [9]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [10]:
def strength(n):
  if n>150:
    return "Strong"
  elif n>100:
    return "Average"
  else:
    return "Weak"

In [11]:
df["Power"]=df["Attack"].apply(strength)

In [12]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Power
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Weak
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Weak
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Weak
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Weak
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Weak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Weak
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Strong
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Average
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Strong
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Average

In [13]:
def defensive(n):
  if n>120:
    return "Defensive"
  elif 80<=n<120:
    return "Avg Defensive"
  else:
    return "less Defensive"

In [14]:
df["Defensive_pokemon"]=df["Defense"].apply(defensive)

In [15]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Power,Defensive_pokemon
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Weak,less Defensive
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Weak,less Defensive
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Weak,Avg Defensive
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Weak,Defensive
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Weak,less Defensive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Weak,Defensive
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Strong,Avg Defensive
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Average,less Defensive
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Strong,less Defensive
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Average,less Defensive

**applymap()it perform the changes in whole table**

In [16]:
df.applymap(type)

/tmp/ipykernel_3957/3828366062.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(type)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Power,Defensive_pokemon
0,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'bool'>,<class 'str'>,<class 'str'>
1,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'bool'>,<class 'str'>,<class 'str'>
2,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'bool'>,<class 'str'>,<class 'str'>
3,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'bool'>,<class 'str'>,<class 'str'>
4,<class 'int'>,<class 'str'>,<class 'str'>,<class 'float'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'bool'>,<class 'str'>,<class 'str'>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'bool'>,<class 'str'>,<class 'str'>
796,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'bool'>,<class 'str'>,<class 'str'>
797,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'bool'>,<class 'str'>,<class 'str'>
798,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'bool'>,<class 'str'>,<class 'str'>
799,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'bool'>,<class 'str'>,<class 'str'>

In [17]:
df.applymap(pd.isnull)

/tmp/ipykernel_3957/436154070.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(pd.isnull)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Power,Defensive_pokemon
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
796,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
797,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
798,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
799,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
newdf=df.applymap(str)

/tmp/ipykernel_3957/995836256.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  newdf=df.applymap(str)

In [19]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   #                  800 non-null    object
 1   Name               800 non-null    object
 2   Type 1             800 non-null    object
 3   Type 2             800 non-null    object
 4   Total              800 non-null    object
 5   HP                 800 non-null    object
 6   Attack             800 non-null    object
 7   Defense            800 non-null    object
 8   Sp. Atk            800 non-null    object
 9   Sp. Def            800 non-null    object
 10  Speed              800 non-null    object
 11  Generation         800 non-null    object
 12  Legendary          800 non-null    object
 13  Power              800 non-null    object
 14  Defensive_pokemon  800 non-null    object
dtypes: object(15)
memory usage: 93.9+ KB

In [20]:
def uppercase(s):
  return s.upper()

In [21]:
newdf.applymap(uppercase)

/tmp/ipykernel_3957/1799477684.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  newdf.applymap(uppercase)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Power,Defensive_pokemon
0,1,BULBASAUR,GRASS,POISON,318,45,49,49,65,65,45,1,FALSE,WEAK,LESS DEFENSIVE
1,2,IVYSAUR,GRASS,POISON,405,60,62,63,80,80,60,1,FALSE,WEAK,LESS DEFENSIVE
2,3,VENUSAUR,GRASS,POISON,525,80,82,83,100,100,80,1,FALSE,WEAK,AVG DEFENSIVE
3,3,VENUSAURMEGA VENUSAUR,GRASS,POISON,625,80,100,123,122,120,80,1,FALSE,WEAK,DEFENSIVE
4,4,CHARMANDER,FIRE,NAN,309,39,52,43,60,50,65,1,FALSE,WEAK,LESS DEFENSIVE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,DIANCIE,ROCK,FAIRY,600,50,100,150,100,150,50,6,TRUE,WEAK,DEFENSIVE
796,719,DIANCIEMEGA DIANCIE,ROCK,FAIRY,700,50,160,110,160,110,110,6,TRUE,STRONG,AVG DEFENSIVE
797,720,HOOPAHOOPA CONFINED,PSYCHIC,GHOST,600,80,110,60,150,130,70,6,TRUE,AVERAGE,LESS DEFENSIVE
798,720,HOOPAHOOPA UNBOUND,PSYCHIC,DARK,680,80,160,60,170,130,80,6,TRUE,STRONG,LESS DEFENSIVE
799,721,VOLCANION,FIRE,WATER,600,80,110,120,130,90,70,6,TRUE,AVERAGE,LESS DEFENSIVE

**map function(it is used for any type of changes in columns value)**

In [22]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Power,Defensive_pokemon
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Weak,less Defensive
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Weak,less Defensive
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Weak,Avg Defensive
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Weak,Defensive
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Weak,less Defensive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Weak,Defensive
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Strong,Avg Defensive
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Average,less Defensive
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Strong,less Defensive
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Average,less Defensive

In [23]:
df["Legendary"]=df["Legendary"].map({True:1,False:0})

In [24]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Power,Defensive_pokemon
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,0,Weak,less Defensive
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,0,Weak,less Defensive
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,0,Weak,Avg Defensive
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,0,Weak,Defensive
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,0,Weak,less Defensive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,1,Weak,Defensive
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,1,Strong,Avg Defensive
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,1,Average,less Defensive
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,1,Strong,less Defensive
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,1,Average,less Defensive

In [25]:
df["Power"]=df["Power"].map({"Weak":0,"Average":1,"Strong":2})

In [26]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Power,Defensive_pokemon
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,0,0,less Defensive
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,0,0,less Defensive
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,0,0,Avg Defensive
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,0,0,Defensive
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,0,0,less Defensive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,1,0,Defensive
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,1,2,Avg Defensive
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,1,1,less Defensive
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,1,2,less Defensive
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,1,1,less Defensive

**repalce() insted of map if you just want to repalce some values inted of mapping all**

In [27]:
df["Generation"]=df["Generation"].replace({1:"First"})

In [28]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Power,Defensive_pokemon
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,First,0,0,less Defensive
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,First,0,0,less Defensive
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,First,0,0,Avg Defensive
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,First,0,0,Defensive
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,First,0,0,less Defensive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,1,0,Defensive
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,1,2,Avg Defensive
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,1,1,less Defensive
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,1,2,less Defensive
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,1,1,less Defensive

**astype function to save memory**

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   #                  800 non-null    int64
 1   Name               800 non-null    object
 2   Type 1             800 non-null    object
 3   Type 2             414 non-null    object
 4   Total              800 non-null    int64
 5   HP                 800 non-null    int64
 6   Attack             800 non-null    int64
 7   Defense            800 non-null    int64
 8   Sp. Atk            800 non-null    int64
 9   Sp. Def            800 non-null    int64
 10  Speed              800 non-null    int64
 11  Generation         800 non-null    object
 12  Legendary          800 non-null    int64
 13  Power              800 non-null    int64
 14  Defensive_pokemon  800 non-null    object
dtypes: int64(10), object(5)
memory usage: 93.9+ KB

In [30]:
df=pd.read_csv("/content/Pokemon.csv")

In [31]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [33]:
df["Generation"]=df["Generation"].astype("int8")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int8
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), int8(1), object(3)
memory usage: 70.4+ KB

In [34]:
df["Total"]=df["Total"].astype("int16")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int16
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int8
 12  Legendary   800 non-null    bool
dtypes: bool(1), int16(1), int64(7), int8(1), object(3)
memory usage: 65.8+ KB

**viwe vs copy**

In [35]:
attackpower=df["Attack"]
attackpower

0       49
1       62
2       82
3      100
4       52
      ...
795    100
796    160
797    110
798    160
799    110
Name: Attack, Length: 800, dtype: int64

In [36]:
attackpower[0:4]="#####"

/tmp/ipykernel_3957/1740285722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attackpower[0:4]="#####"
/tmp/ipykernel_3957/1740285722.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '#####' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attackpower[0:4]="#####"

In [37]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,#####,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,#####,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,#####,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,#####,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

### **viwe means if you create a another variable so by default it is viwe and in a viwe changes in one variable reflect to other variable refrence because they are same and also have same memoery address**

In [38]:
df=pd.read_csv("/content/Pokemon.csv")

In [39]:
attackpower=df["Attack"].copy()
attackpower

0       49
1       62
2       82
3      100
4       52
      ...
795    100
796    160
797    110
798    160
799    110
Name: Attack, Length: 800, dtype: int64

In [40]:
attackpower[0:5]="@@@@"

/tmp/ipykernel_3957/236788111.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '@@@@' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attackpower[0:5]="@@@@"

In [41]:
attackpower

0      @@@@
1      @@@@
2      @@@@
3      @@@@
4      @@@@
       ...
795     100
796     160
797     110
798     160
799     110
Name: Attack, Length: 800, dtype: object

In [42]:
df["Attack"]

0       49
1       62
2       82
3      100
4       52
      ...
795    100
796    160
797    110
798    160
799    110
Name: Attack, Length: 800, dtype: int64

**in copy changes in other variable do not refelct to its refrence VARIABLE because copy make an seprate memory location and it is not conncetd  to the same variable it make its own space**

## **String funtions in pandas[]**

In [43]:
#s.upper() to capitalize all the char in string
#s.lower() to convert in samll letter
#s.swapcase() capital is convert to small and samll is convert to capital
#s.title() first word capital
#s.captilize() only first word capital
s="my Name is AbhaY DwiVEdi"
s=s.capitalize()
print(s)
s=s.upper()
print(s)
s=s.lower()
print(s)
s=s.title()
print(s)
s=s.swapcase()
print(s)

My name is abhay dwivedi
MY NAME IS ABHAY DWIVEDI
my name is abhay dwivedi
My Name Is Abhay Dwivedi
mY nAME iS aBHAY dWIVEDI

In [44]:
df["Name"]=df["Name"].str.upper()
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,BULBASAUR,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,IVYSAUR,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,VENUSAUR,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VENUSAURMEGA VENUSAUR,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,CHARMANDER,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,DIANCIE,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DIANCIEMEGA DIANCIE,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HOOPAHOOPA CONFINED,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HOOPAHOOPA UNBOUND,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,VOLCANION,Fire,Water,600,80,110,120,130,90,70,6,True

In [45]:
df["Name"]=df["Name"].str.lower()
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,venusaurmega venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,dianciemega diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,hoopahoopa confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,hoopahoopa unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [46]:
df["Name"]=df["Name"].str.title()
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Venusaurmega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,Dianciemega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,Hoopahoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,Hoopahoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [47]:
df["Name"]=df["Name"].str.swapcase()
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,bULBASAUR,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,iVYSAUR,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,vENUSAUR,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,vENUSAURMEGA vENUSAUR,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,cHARMANDER,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,dIANCIE,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,dIANCIEMEGA dIANCIE,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,hOOPAHOOPA cONFINED,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,hOOPAHOOPA uNBOUND,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,vOLCANION,Fire,Water,600,80,110,120,130,90,70,6,True

In [48]:
df["Type 1"]=df["Type 1"].str.swapcase()
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,bULBASAUR,gRASS,Poison,318,45,49,49,65,65,45,1,False
1,2,iVYSAUR,gRASS,Poison,405,60,62,63,80,80,60,1,False
2,3,vENUSAUR,gRASS,Poison,525,80,82,83,100,100,80,1,False
3,3,vENUSAURMEGA vENUSAUR,gRASS,Poison,625,80,100,123,122,120,80,1,False
4,4,cHARMANDER,fIRE,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,dIANCIE,rOCK,Fairy,600,50,100,150,100,150,50,6,True
796,719,dIANCIEMEGA dIANCIE,rOCK,Fairy,700,50,160,110,160,110,110,6,True
797,720,hOOPAHOOPA cONFINED,pSYCHIC,Ghost,600,80,110,60,150,130,70,6,True
798,720,hOOPAHOOPA uNBOUND,pSYCHIC,Dark,680,80,160,60,170,130,80,6,True
799,721,vOLCANION,fIRE,Water,600,80,110,120,130,90,70,6,True

## **startswith and endwith**

In [49]:
df=pd.read_csv("/content/Pokemon.csv")
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [50]:
df[df["Name"].str.startswith("Pik")]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False

In [51]:
newdf=df[df["Name"].str.startswith("Ab")]
newdf

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False

In [52]:
newdf=df[df["Name"].str.endswith("y")]
newdf

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
40,35,Clefairy,Fairy,NaN,323,70,45,48,60,65,35,1,False
61,56,Mankey,Fighting,NaN,305,40,80,35,35,45,70,1,False
99,92,Gastly,Ghost,Poison,310,30,35,30,100,35,80,1,False
106,98,Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
194,180,Flaaffy,Electric,NaN,365,70,55,55,80,60,45,2,False
242,224,Octillery,Water,NaN,480,75,105,75,105,75,45,2,False
245,227,Skarmory,Steel,Flying,465,65,80,140,40,70,70,2,False
250,231,Phanpy,Ground,NaN,330,90,60,60,40,40,40,2,False
259,240,Magby,Fire,NaN,365,45,75,37,70,55,83,2,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
290,267,Beautifly,Bug,Flying,395,60,70,50,100,50,65,3,False
298,275,Shiftry,Grass,Dark,480,90,100,60,90,60,80,3,False
324,300,Skitty,Normal,NaN,260,50,45,45,35,35,50,3,False
325,301,Delcatty,Normal,NaN,380,70,65,65,55,55,70,3,False
375,343,Baltoy,Ground,Psychic,300,40,40,55,40,70,55,3,False
378,346,Cradily,Rock,Grass,495,86,81,97,81,107,43,3,False
441,396,Starly,Normal,Flying,245,40,55,30,30,30,60,4,False
450,405,Luxray,Electric,NaN,523,80,120,79,95,79,70,4,False
457,412,Burmy,Bug,NaN,224,40,29,45,29,45,36,4,False
474,427,Buneary,Normal,NaN,350,55,66,44,44,56,85,4,False
475,428,Lopunny,Normal,NaN,480,65,76,84,54,96,105,4,False
476,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,False
480,432,Purugly,Normal,NaN,452,71,82,64,64,59,112,4,False
482,434,Stunky,Poison,Dark,329,63,63,47,41,41,74,4,False
486,438,Bonsly,Rock,NaN,290,50,80,95,10,45,10,4,False
488,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False
514,463,Lickilicky,Normal,NaN,515,110,85,95,80,95,50,4,False
548,490,Manaphy,Water,NaN,600,100,100,100,100,100,100,4,False
554,495,Snivy,Grass,NaN,308,45,45,55,45,55,63,5,False
602,542,Leavanny,Bug,Grass,500,75,103,80,70,80,92,5,False
620,559,Scraggy,Dark,Fighting,348,50,75,70,35,70,48,5,False
621,560,Scrafty,Dark,Fighting,488,65,90,115,45,115,58,5,False
689,628,Braviary,Normal,Flying,510,100,123,75,57,75,80,5,False
690,629,Vullaby,Dark,Flying,370,70,55,75,45,65,60,5,False
727,659,Bunnelby,Normal,NaN,237,38,36,38,32,36,57,6,False
728,660,Diggersby,Normal,Ground,423,85,56,77,50,77,78,6,False
756,686,Inkay,Dark,Psychic,288,53,54,53,37,46,45,6,False
774,704,Goomy,Dragon,NaN,300,45,50,35,55,75,40,6,False

**olympics dataset**

In [53]:
df=pd.read_csv("/content/olympics.csv",sep=";")
df

   Country  2021  2022  2023  2024
0   France     1     4     2     1
1      USA     3     2     1     1
2  Germany     2     1     4     2
3    Japan     3     4     2     2
4   Canada     5     2     5     2
5    India     1     4     5     3

In [54]:
df[df["Country"].str.endswith("a")]

  Country  2021  2022  2023  2024
4  Canada     5     2     5     2
5   India     1     4     5     3

In [55]:
#contains it is used for any specific word
df[df["Country"].str.contains("a",case=False)]

   Country  2021  2022  2023  2024
0   France     1     4     2     1
1      USA     3     2     1     1
2  Germany     2     1     4     2
3    Japan     3     4     2     2
4   Canada     5     2     5     2
5    India     1     4     5     3

In [56]:
df=pd.read_csv("/content/Pokemon.csv")
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [57]:
#i want to conver all the columns name in lower case
df.columns=df.columns.str.capitalize()
df

,#,Name,Type 1,Type 2,Total,Hp,Attack,Defense,Sp. atk,Sp. def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [58]:
df

,#,Name,Type 1,Type 2,Total,Hp,Attack,Defense,Sp. atk,Sp. def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [59]:
#fecth the 2 generation pokemon
nwedf = df[df["Generation"]==2]
newdf

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
40,35,Clefairy,Fairy,NaN,323,70,45,48,60,65,35,1,False
61,56,Mankey,Fighting,NaN,305,40,80,35,35,45,70,1,False
99,92,Gastly,Ghost,Poison,310,30,35,30,100,35,80,1,False
106,98,Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
194,180,Flaaffy,Electric,NaN,365,70,55,55,80,60,45,2,False
242,224,Octillery,Water,NaN,480,75,105,75,105,75,45,2,False
245,227,Skarmory,Steel,Flying,465,65,80,140,40,70,70,2,False
250,231,Phanpy,Ground,NaN,330,90,60,60,40,40,40,2,False
259,240,Magby,Fire,NaN,365,45,75,37,70,55,83,2,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
290,267,Beautifly,Bug,Flying,395,60,70,50,100,50,65,3,False
298,275,Shiftry,Grass,Dark,480,90,100,60,90,60,80,3,False
324,300,Skitty,Normal,NaN,260,50,45,45,35,35,50,3,False
325,301,Delcatty,Normal,NaN,380,70,65,65,55,55,70,3,False
375,343,Baltoy,Ground,Psychic,300,40,40,55,40,70,55,3,False
378,346,Cradily,Rock,Grass,495,86,81,97,81,107,43,3,False
441,396,Starly,Normal,Flying,245,40,55,30,30,30,60,4,False
450,405,Luxray,Electric,NaN,523,80,120,79,95,79,70,4,False
457,412,Burmy,Bug,NaN,224,40,29,45,29,45,36,4,False
474,427,Buneary,Normal,NaN,350,55,66,44,44,56,85,4,False
475,428,Lopunny,Normal,NaN,480,65,76,84,54,96,105,4,False
476,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,False
480,432,Purugly,Normal,NaN,452,71,82,64,64,59,112,4,False
482,434,Stunky,Poison,Dark,329,63,63,47,41,41,74,4,False
486,438,Bonsly,Rock,NaN,290,50,80,95,10,45,10,4,False
488,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False
514,463,Lickilicky,Normal,NaN,515,110,85,95,80,95,50,4,False
548,490,Manaphy,Water,NaN,600,100,100,100,100,100,100,4,False
554,495,Snivy,Grass,NaN,308,45,45,55,45,55,63,5,False
602,542,Leavanny,Bug,Grass,500,75,103,80,70,80,92,5,False
620,559,Scraggy,Dark,Fighting,348,50,75,70,35,70,48,5,False
621,560,Scrafty,Dark,Fighting,488,65,90,115,45,115,58,5,False
689,628,Braviary,Normal,Flying,510,100,123,75,57,75,80,5,False
690,629,Vullaby,Dark,Flying,370,70,55,75,45,65,60,5,False
727,659,Bunnelby,Normal,NaN,237,38,36,38,32,36,57,6,False
728,660,Diggersby,Normal,Ground,423,85,56,77,50,77,78,6,False
756,686,Inkay,Dark,Psychic,288,53,54,53,37,46,45,6,False
774,704,Goomy,Dragon,NaN,300,45,50,35,55,75,40,6,False

In [60]:
NewDF=df[df["Generation"]==2]
NewDF

,#,Name,Type 1,Type 2,Total,Hp,Attack,Defense,Sp. atk,Sp. def,Speed,Generation,Legendary
166,152,Chikorita,Grass,NaN,318,45,49,65,49,65,45,2,False
167,153,Bayleef,Grass,NaN,405,60,62,80,63,80,60,2,False
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
169,155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,248,Tyranitar,Rock,Dark,600,100,134,110,95,100,61,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
269,249,Lugia,Psychic,Flying,680,106,90,130,90,154,110,2,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
271,251,Celebi,Psychic,Grass,600,100,100,100,100,100,100,2,False

In [61]:
#display the pokemon where type 1 is fire
Pokemontype=df[df["Type 1"]=="Fire"]
Pokemontype

,#,Name,Type 1,Type 2,Total,Hp,Attack,Defense,Sp. atk,Sp. def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,350,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,410,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,500,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,495,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,525,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,534,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,250,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,410,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,365,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,310,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,405,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,305,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,460,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,470,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,309,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,405,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,534,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,540,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,308,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,316,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,498,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,315,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,480,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,484,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,307,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,409,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,534,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,382,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,499,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## **value_counts(it workd as a groupby)**

In [62]:
df["Type 1"].value_counts()

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Ground       32
Ghost        32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

In [63]:
df["Type 2"].value_counts()

Type 2
Flying      97
Ground      35
Poison      34
Psychic     33
Fighting    26
Grass       25
Fairy       23
Steel       22
Dark        20
Dragon      18
Ice         14
Rock        14
Water       14
Ghost       14
Fire        12
Electric     6
Normal       4
Bug          3
Name: count, dtype: int64

# **Joins**

In [64]:
import pandas as pd