In [209]:
#import pandas
import pandas as pd

# **Sereis(pd.Series)**

In [210]:
#making Series using list
s=["Abhay","Deepa","Mihika","Lucky"]
S=pd.Series(s)
S

0     Abhay
1     Deepa
2    Mihika
3     Lucky
dtype: object

In [211]:
dict={"abhay":22,"deepa":23,"mihika":24}
s=pd.Series(dict)
s

abhay     22
deepa     23
mihika    24
dtype: int64

In [212]:
DAY=["SUN","MON","TUES","WED","THU","FRI","SAT"]
BREAKFAST=["POHA","JALEBI","IDLE","DOSA","EGGS","HALWA","SPRAUTS"]
s=pd.Series(data=BREAKFAST,index=DAY)
print(s)
print(s.dtype)
print(s.size)
print(s.shape)
print(s.ndim)

SUN        POHA
MON      JALEBI
TUES       IDLE
WED        DOSA
THU        EGGS
FRI       HALWA
SAT     SPRAUTS
dtype: object
object
7
(7,)
1

In [213]:
marks={"a":22,"b":24,"c":21}
s=pd.Series(marks)
s

a    22
b    24
c    21
dtype: int64

In [214]:
s.sum()#sum of all elements

np.int64(67)

In [215]:
s.prod()#product of all elements in Sereis

np.int64(11088)

In [216]:
s.mean()#avg of all elements in Sereis

np.float64(22.333333333333332)

In [217]:
s.median()#median of all elements

22.0

In [218]:
s.std()#satndard

1.5275252316519465

In [219]:
s.dtype#type of elements in Sereis

dtype('int64')

In [220]:
s.max()#max element in Sereis

24

In [221]:
s.min()#min element in Sereis

21

In [222]:
s.idxmax()

'b'

In [223]:
s.idxmin()

'c'

In [224]:
s.argmax()

np.int64(1)

In [225]:
s.argmin()

np.int64(2)

In [226]:
s.isnull()#check nan values

a    False
b    False
c    False
dtype: bool

In [227]:
s.hasnans

False

In [228]:
s.is_unique#chack every element is unique

True

In [229]:
s.round(1)

a    22
b    24
c    21
dtype: int64

In [230]:
s.values#directly fetch the values

array([22, 24, 21])

In [231]:
s.keys()# dict keys

Index(['a', 'b', 'c'], dtype='object')

# **Work on csv files(pd.read_csv)**

In [232]:
#in data frame
df=pd.read_csv("/content/TopRichestInWorld.csv")
df

,Name,NetWorth,Age,Country/Territory,Source,Industry
0,Elon Musk,"$219,000,000,000",50,United States,"Tesla, SpaceX",Automotive
1,Jeff Bezos,"$171,000,000,000",58,United States,Amazon,Technology
2,Bernard Arnault & family,"$158,000,000,000",73,France,LVMH,Fashion & Retail
3,Bill Gates,"$129,000,000,000",66,United States,Microsoft,Technology
4,Warren Buffett,"$118,000,000,000",91,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...
96,Vladimir Potanin,"$17,300,000,000",61,Russia,metals,Metals & Mining
97,Harold Hamm & family,"$17,200,000,000",76,United States,oil & gas,Energy
98,Sun Piaoyang,"$17,100,000,000",63,China,pharmaceuticals,Healthcare
99,Luo Liguo & family,"$17,000,000,000",66,China,chemicals,Manufacturing
100,Peter Woo,"$17,000,000,000",75,Hong Kong,real estate,Real Estate

In [233]:
#to select one single column
df["Name"]

0                     Elon Musk
1                    Jeff Bezos
2      Bernard Arnault & family
3                    Bill Gates
4                Warren Buffett
                 ...
96             Vladimir Potanin
97         Harold Hamm & family
98                 Sun Piaoyang
99           Luo Liguo & family
100                   Peter Woo
Name: Name, Length: 101, dtype: object

In [234]:
#select multiple columns
df=pd.read_csv("/content/TopRichestInWorld.csv",usecols=["Name","NetWorth","Age"])
df

                         Name          NetWorth  Age
0                   Elon Musk  $219,000,000,000   50
1                  Jeff Bezos  $171,000,000,000   58
2    Bernard Arnault & family  $158,000,000,000   73
3                  Bill Gates  $129,000,000,000   66
4              Warren Buffett  $118,000,000,000   91
..                        ...               ...  ...
96           Vladimir Potanin   $17,300,000,000   61
97       Harold Hamm & family   $17,200,000,000   76
98               Sun Piaoyang   $17,100,000,000   63
99         Luo Liguo & family   $17,000,000,000   66
100                 Peter Woo   $17,000,000,000   75

[101 rows x 3 columns]

In [235]:
#fetch top 5 record by default
df.head()

                       Name          NetWorth  Age
0                 Elon Musk  $219,000,000,000   50
1                Jeff Bezos  $171,000,000,000   58
2  Bernard Arnault & family  $158,000,000,000   73
3                Bill Gates  $129,000,000,000   66
4            Warren Buffett  $118,000,000,000   91

In [236]:
df.head(10)

                       Name          NetWorth  Age
0                 Elon Musk  $219,000,000,000   50
1                Jeff Bezos  $171,000,000,000   58
2  Bernard Arnault & family  $158,000,000,000   73
3                Bill Gates  $129,000,000,000   66
4            Warren Buffett  $118,000,000,000   91
5                Larry Page  $111,000,000,000   49
6               Sergey Brin  $107,000,000,000   48
7             Larry Ellison  $106,000,000,000   77
8             Steve Ballmer   $91,400,000,000   66
9             Mukesh Ambani   $90,700,000,000   64

In [237]:
#to delete last record
df.head(-90)

                        Name          NetWorth  Age
0                  Elon Musk  $219,000,000,000   50
1                 Jeff Bezos  $171,000,000,000   58
2   Bernard Arnault & family  $158,000,000,000   73
3                 Bill Gates  $129,000,000,000   66
4             Warren Buffett  $118,000,000,000   91
5                 Larry Page  $111,000,000,000   49
6                Sergey Brin  $107,000,000,000   48
7              Larry Ellison  $106,000,000,000   77
8              Steve Ballmer   $91,400,000,000   66
9              Mukesh Ambani   $90,700,000,000   64
10     Gautam Adani & family   $90,000,000,000   59

In [238]:
# to fetch records from bottom
df.tail()

                     Name         NetWorth  Age
96       Vladimir Potanin  $17,300,000,000   61
97   Harold Hamm & family  $17,200,000,000   76
98           Sun Piaoyang  $17,100,000,000   63
99     Luo Liguo & family  $17,000,000,000   66
100             Peter Woo  $17,000,000,000   75

In [239]:
df.tail(10)

                        Name         NetWorth  Age
91   Savitri Jindal & family  $17,700,000,000   72
92               Wang Wenyin  $17,700,000,000   54
93                 Li Xiting  $17,600,000,000   71
94            Stefan Persson  $17,600,000,000   74
95               Steve Cohen  $17,400,000,000   65
96          Vladimir Potanin  $17,300,000,000   61
97      Harold Hamm & family  $17,200,000,000   76
98              Sun Piaoyang  $17,100,000,000   63
99        Luo Liguo & family  $17,000,000,000   66
100                Peter Woo  $17,000,000,000   75

In [240]:
#delete top records
df.tail(-96)

                     Name         NetWorth  Age
96       Vladimir Potanin  $17,300,000,000   61
97   Harold Hamm & family  $17,200,000,000   76
98           Sun Piaoyang  $17,100,000,000   63
99     Luo Liguo & family  $17,000,000,000   66
100             Peter Woo  $17,000,000,000   75

In [241]:
#convert to sereis (squeeze())
s=pd.read_csv("/content/TopRichestInWorld.csv",usecols=["Name","Age"]).squeeze()
print(s)

                         Name  Age
0                   Elon Musk   50
1                  Jeff Bezos   58
2    Bernard Arnault & family   73
3                  Bill Gates   66
4              Warren Buffett   91
..                        ...  ...
96           Vladimir Potanin   61
97       Harold Hamm & family   76
98               Sun Piaoyang   63
99         Luo Liguo & family   66
100                 Peter Woo   75

[101 rows x 2 columns]

In [242]:
#for sorting the values
df.sort_values("Name")#by default ascending

                    Name          NetWorth  Age
74       Abigail Johnson   $21,200,000,000   60
42      Alain Wertheimer   $31,200,000,000   73
17          Alice Walton   $65,300,000,000   72
22        Amancio Ortega   $59,600,000,000   86
89        Andrew Forrest   $17,800,000,000   60
..                   ...               ...  ...
4         Warren Buffett  $118,000,000,000   91
54      William Lei Ding   $25,200,000,000   50
85  Yang Huiyan & family   $18,700,000,000   40
24          Zhang Yiming   $50,000,000,000   38
16        Zhong Shanshan   $65,700,000,000   67

[101 rows x 3 columns]

In [243]:
df.sort_values("Name", ascending=False)

                    Name          NetWorth  Age
16        Zhong Shanshan   $65,700,000,000   67
24          Zhang Yiming   $50,000,000,000   38
85  Yang Huiyan & family   $18,700,000,000   40
54      William Lei Ding   $25,200,000,000   50
4         Warren Buffett  $118,000,000,000   91
..                   ...               ...  ...
89        Andrew Forrest   $17,800,000,000   60
22        Amancio Ortega   $59,600,000,000   86
17          Alice Walton   $65,300,000,000   72
42      Alain Wertheimer   $31,200,000,000   73
74       Abigail Johnson   $21,200,000,000   60

[101 rows x 3 columns]

In [244]:
df.sort_values("Name",kind="Qucik sort")#for specific type of sorting

                    Name          NetWorth  Age
74       Abigail Johnson   $21,200,000,000   60
42      Alain Wertheimer   $31,200,000,000   73
17          Alice Walton   $65,300,000,000   72
22        Amancio Ortega   $59,600,000,000   86
89        Andrew Forrest   $17,800,000,000   60
..                   ...               ...  ...
4         Warren Buffett  $118,000,000,000   91
54      William Lei Ding   $25,200,000,000   50
85  Yang Huiyan & family   $18,700,000,000   40
24          Zhang Yiming   $50,000,000,000   38
16        Zhong Shanshan   $65,700,000,000   67

[101 rows x 3 columns]

In [245]:
df=pd.read_csv("/content/TopRichestInWorld.csv",usecols=["Industry"])
df

                  Industry
0               Automotive
1               Technology
2         Fashion & Retail
3               Technology
4    Finance & Investments
..                     ...
96         Metals & Mining
97                  Energy
98              Healthcare
99           Manufacturing
100            Real Estate

[101 rows x 1 columns]

In [246]:
df.value_counts()#it wroks as a groupby command

Industry
Fashion & Retail         18
Technology               15
Finance & Investments    13
Metals & Mining           9
Food & Beverage           8
Automotive                7
Diversified               6
Healthcare                5
Manufacturing             5
Media & Entertainment     4
Real Estate               3
Energy                    2
Telecom                   2
Logistics                 2
Gambling & Casinos        1
Service                   1
Name: count, dtype: int64

In [247]:
df.value_counts(normalize=True)#normalize give the contribution between 0 to 1

Industry
Fashion & Retail         0.178218
Technology               0.148515
Finance & Investments    0.128713
Metals & Mining          0.089109
Food & Beverage          0.079208
Automotive               0.069307
Diversified              0.059406
Healthcare               0.049505
Manufacturing            0.049505
Media & Entertainment    0.039604
Real Estate              0.029703
Energy                   0.019802
Telecom                  0.019802
Logistics                0.019802
Gambling & Casinos       0.009901
Service                  0.009901
Name: proportion, dtype: float64

# **DataFrame Part 1**

In [248]:
#to import
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [249]:
d={"a":[10,20,30],"b":[40,50,60],"c":[70,80,90]}
df=pd.DataFrame(d)
df

    a   b   c
0  10  40  70
1  20  50  80
2  30  60  90

In [250]:
df.sum()#by default provide sum in column wise

a     60
b    150
c    240
dtype: int64

In [251]:
df.sum(axis=1)#sum row wise

0    120
1    150
2    180
dtype: int64

In [252]:
df.sum().sum()#sum of whole df

np.int64(450)

In [253]:
df.prod()

a      6000
b    120000
c    504000
dtype: int64

In [254]:
df.median()

a    20.0
b    50.0
c    80.0
dtype: float64

In [255]:
df.min()

a    10
b    40
c    70
dtype: int64

In [256]:
df.max()

a    30
b    60
c    90
dtype: int64

In [257]:
df.std()

a    10.0
b    10.0
c    10.0
dtype: float64

In [258]:
df.isnull()# to check null values

       a      b      c
0  False  False  False
1  False  False  False
2  False  False  False

In [259]:
df.all

<bound method DataFrame.all of     a   b   c
0  10  40  70
1  20  50  80
2  30  60  90>

In [260]:
df.dtypes#to check data types

a    int64
b    int64
c    int64
dtype: object

In [261]:
type(df)# to check type

pandas.core.frame.DataFrame

**Working on IMDB dataset**

In [262]:
df=pd.read_csv("/content/imdb1000.csv")
df

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [263]:
df=pd.read_csv("/content/imdb1000.csv",usecols=["Series_Title","Genre","IMDB_Rating","Runtime","Gross"])
df

,Series_Title,Runtime,Genre,IMDB_Rating,Gross
0,The Shawshank Redemption,142 min,Drama,9.3,"28,341,469"
1,The Godfather,175 min,"Crime, Drama",9.2,"134,966,411"
2,The Dark Knight,152 min,"Action, Crime, Drama",9.0,"534,858,444"
3,The Godfather: Part II,202 min,"Crime, Drama",9.0,"57,300,000"
4,12 Angry Men,96 min,"Crime, Drama",9.0,"4,360,000"
...,...,...,...,...,...
995,Breakfast at Tiffany's,115 min,"Comedy, Drama, Romance",7.6,NaN
996,Giant,201 min,"Drama, Western",7.6,NaN
997,From Here to Eternity,118 min,"Drama, Romance, War",7.6,"30,500,000"
998,Lifeboat,97 min,"Drama, War",7.6,NaN
999,The 39 Steps,86 min,"Crime, Mystery, Thriller",7.6,NaN

In [264]:
#to set index
df.set_index(["Series_Title"],inplace=True)

In [265]:
df

,Runtime,Genre,IMDB_Rating,Gross
Series_Title,,,,
The Shawshank Redemption,142 min,Drama,9.3,"28,341,469"
The Godfather,175 min,"Crime, Drama",9.2,"134,966,411"
The Dark Knight,152 min,"Action, Crime, Drama",9.0,"534,858,444"
The Godfather: Part II,202 min,"Crime, Drama",9.0,"57,300,000"
12 Angry Men,96 min,"Crime, Drama",9.0,"4,360,000"
...,...,...,...,...
Breakfast at Tiffany's,115 min,"Comedy, Drama, Romance",7.6,NaN
Giant,201 min,"Drama, Western",7.6,NaN
From Here to Eternity,118 min,"Drama, Romance, War",7.6,"30,500,000"
Lifeboat,97 min,"Drama, War",7.6,NaN
The 39 Steps,86 min,"Crime, Mystery, Thriller",7.6,NaN

In [266]:
#for structure summery
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, The Shawshank Redemption to The 39 Steps
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Runtime      1000 non-null   object
 1   Genre        1000 non-null   object
 2   IMDB_Rating  1000 non-null   float64
 3   Gross        831 non-null    object
dtypes: float64(1), object(3)
memory usage: 39.1+ KB

In [267]:
df.describe()#to provide the states result means in numeric only

       IMDB_Rating
count  1000.000000
mean      7.949300
std       0.275491
min       7.600000
25%       7.700000
50%       7.900000
75%       8.100000
max       9.300000

In [268]:
#now i want to convert runtime object into int=64 it total have 3 steps
df["Runtime"]=df["Runtime"].str.replace("min","")

In [269]:
df

,Runtime,Genre,IMDB_Rating,Gross
Series_Title,,,,
The Shawshank Redemption,142,Drama,9.3,"28,341,469"
The Godfather,175,"Crime, Drama",9.2,"134,966,411"
The Dark Knight,152,"Action, Crime, Drama",9.0,"534,858,444"
The Godfather: Part II,202,"Crime, Drama",9.0,"57,300,000"
12 Angry Men,96,"Crime, Drama",9.0,"4,360,000"
...,...,...,...,...
Breakfast at Tiffany's,115,"Comedy, Drama, Romance",7.6,NaN
Giant,201,"Drama, Western",7.6,NaN
From Here to Eternity,118,"Drama, Romance, War",7.6,"30,500,000"
Lifeboat,97,"Drama, War",7.6,NaN
The 39 Steps,86,"Crime, Mystery, Thriller",7.6,NaN

In [270]:
#step to fill naLL VALUE IF HAVE SO USE fillna()
#it dont habe any null value so i preferd to jump on 3rd step
#convert data type so use .astype()
df["Runtime"]=df["Runtime"].astype("int64")

In [271]:
df.describe()

           Runtime  IMDB_Rating
count  1000.000000  1000.000000
mean    122.891000     7.949300
std      28.093671     0.275491
min      45.000000     7.600000
25%     103.000000     7.700000
50%     119.000000     7.900000
75%     137.000000     8.100000
max     321.000000     9.300000

In [272]:
df

,Runtime,Genre,IMDB_Rating,Gross
Series_Title,,,,
The Shawshank Redemption,142,Drama,9.3,"28,341,469"
The Godfather,175,"Crime, Drama",9.2,"134,966,411"
The Dark Knight,152,"Action, Crime, Drama",9.0,"534,858,444"
The Godfather: Part II,202,"Crime, Drama",9.0,"57,300,000"
12 Angry Men,96,"Crime, Drama",9.0,"4,360,000"
...,...,...,...,...
Breakfast at Tiffany's,115,"Comedy, Drama, Romance",7.6,NaN
Giant,201,"Drama, Western",7.6,NaN
From Here to Eternity,118,"Drama, Romance, War",7.6,"30,500,000"
Lifeboat,97,"Drama, War",7.6,NaN
The 39 Steps,86,"Crime, Mystery, Thriller",7.6,NaN

In [273]:
#now i want to repalce data type of gross
#step one
df["Gross"]=df["Gross"].str.replace(",","")

In [274]:
#step2
df["Gross"]=df["Gross"].fillna(0)

In [275]:
#step 3
df["Gross"]=df["Gross"].astype("int64")

In [276]:
df.describe().round(1)

       Runtime  IMDB_Rating        Gross
count   1000.0       1000.0       1000.0
mean     122.9          7.9   56536878.0
std       28.1          0.3  103238179.5
min       45.0          7.6          0.0
25%      103.0          7.7     445709.8
50%      119.0          7.9   10702751.5
75%      137.0          8.1   61539891.2
max      321.0          9.3  936662225.0

In [277]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, The Shawshank Redemption to The 39 Steps
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Runtime      1000 non-null   int64
 1   Genre        1000 non-null   object
 2   IMDB_Rating  1000 non-null   float64
 3   Gross        1000 non-null   int64
dtypes: float64(1), int64(2), object(1)
memory usage: 39.1+ KB

In [278]:
df.nlargest(10,columns="Gross")#to fecth top 10 records

,Runtime,Genre,IMDB_Rating,Gross
Series_Title,,,,
Star Wars: Episode VII - The Force Awakens,138,"Action, Adventure, Sci-Fi",7.9,936662225
Avengers: Endgame,181,"Action, Adventure, Drama",8.4,858373000
Avatar,162,"Action, Adventure, Fantasy",7.8,760507625
Avengers: Infinity War,149,"Action, Adventure, Sci-Fi",8.4,678815482
Titanic,194,"Drama, Romance",7.8,659325379
The Avengers,143,"Action, Adventure, Sci-Fi",8.0,623279547
Incredibles 2,118,"Animation, Action, Adventure",7.6,608581744
The Dark Knight,152,"Action, Crime, Drama",9.0,534858444
Rogue One,133,"Action, Adventure, Sci-Fi",7.8,532177324
The Dark Knight Rises,164,"Action, Adventure",8.4,448139099

In [279]:
#df.nsmallest()fetch last records
df.nsmallest(10,"Gross")

,Runtime,Genre,IMDB_Rating,Gross
Series_Title,,,,
Hamilton,160,"Biography, Drama, History",8.6,0
Soorarai Pottru,153,Drama,8.6,0
Seppuku,133,"Action, Drama, Mystery",8.6,0
It's a Wonderful Life,130,"Drama, Family, Fantasy",8.6,0
Hotaru no haka,89,"Animation, Drama, War",8.5,0
Ayla: The Daughter of War,125,"Biography, Drama, History",8.4,0
Vikram Vedha,147,"Action, Crime, Drama",8.4,0
Anand,122,"Drama, Musical",8.4,0
Tengoku to jigoku,143,"Crime, Drama, Mystery",8.4,0
Paths of Glory,88,"Drama, War",8.4,0

In [280]:
df.dropna()#it is used to drop nan values

,Runtime,Genre,IMDB_Rating,Gross
Series_Title,,,,
The Shawshank Redemption,142,Drama,9.3,28341469
The Godfather,175,"Crime, Drama",9.2,134966411
The Dark Knight,152,"Action, Crime, Drama",9.0,534858444
The Godfather: Part II,202,"Crime, Drama",9.0,57300000
12 Angry Men,96,"Crime, Drama",9.0,4360000
...,...,...,...,...
Breakfast at Tiffany's,115,"Comedy, Drama, Romance",7.6,0
Giant,201,"Drama, Western",7.6,0
From Here to Eternity,118,"Drama, Romance, War",7.6,30500000
Lifeboat,97,"Drama, War",7.6,0
The 39 Steps,86,"Crime, Mystery, Thriller",7.6,0

In [281]:
df.drop(columns="Genre")# to delete any specific column by default it is viwe so if permamently delte so use inpalce =True

                          Runtime  IMDB_Rating      Gross
Series_Title
The Shawshank Redemption      142          9.3   28341469
The Godfather                 175          9.2  134966411
The Dark Knight               152          9.0  534858444
The Godfather: Part II        202          9.0   57300000
12 Angry Men                   96          9.0    4360000
...                           ...          ...        ...
Breakfast at Tiffany's        115          7.6          0
Giant                         201          7.6          0
From Here to Eternity         118          7.6   30500000
Lifeboat                       97          7.6          0
The 39 Steps                   86          7.6          0

[1000 rows x 3 columns]

# **Work with excel files**

In [282]:
#for read old excel file use
import xlrd

In [283]:
#excel files have two types
#.xls old files
#.xlxs new files

In [284]:
#to read them
df=pd.read_excel("/content/titanic.xls")
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [285]:
#for one specific column
df["name"]

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

In [286]:
#for access multiple columns use usecols=[]
df=pd.read_excel("/content/titanic.xls",usecols=["name","sex","pclass","survived","age","fare","body"])

In [287]:
df

,pclass,survived,name,sex,age,fare,body
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,211.3375,NaN
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,151.5500,NaN
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,151.5500,NaN
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,151.5500,135.0
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,151.5500,NaN
...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,14.4542,328.0
1305,3,0,"Zabour, Miss. Thamine",female,NaN,14.4542,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,7.2250,304.0
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,7.2250,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,7.8750,NaN

In [288]:
#loc or iloc
# loc work with columns names
#iloc wrok with index values you also perform slicing on this
df.iloc[1]

pclass                                   1
survived                                 1
name        Allison, Master. Hudson Trevor
sex                                   male
age                                 0.9167
fare                                151.55
body                                   NaN
Name: 1, dtype: object

In [289]:
df.loc[1]

pclass                                   1
survived                                 1
name        Allison, Master. Hudson Trevor
sex                                   male
age                                 0.9167
fare                                151.55
body                                   NaN
Name: 1, dtype: object

In [290]:
df.iloc[1:5]

,pclass,survived,name,sex,age,fare,body
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,151.55,NaN
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,151.55,NaN
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,151.55,135.0
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,151.55,NaN

In [291]:
df.loc[1:5]

,pclass,survived,name,sex,age,fare,body
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,151.55,NaN
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,151.55,NaN
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,151.55,135.0
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,151.55,NaN
5,1,1,"Anderson, Mr. Harry",male,48.0000,26.55,NaN

In [292]:
#now you use both wrok same but in column they dont work perfectly
df.iloc[1:5, 1:4]

   survived                                             name     sex
1         1                   Allison, Master. Hudson Trevor    male
2         0                     Allison, Miss. Helen Loraine  female
3         0             Allison, Mr. Hudson Joshua Creighton    male
4         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female

### Fetching a single column
You can access a single column by using square brackets with the column name. This will return a pandas Series.

In [293]:
display(df["name"]) # Fetching the 'name' column

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

### Fetching multiple columns
To fetch multiple columns, you need to pass a list of column names inside the square brackets. This will return a new DataFrame containing only those columns.

In [294]:
display(df[["name", "age", "sex"]]) # Fetching 'name', 'age', and 'sex' columns

                                                 name      age     sex
0                       Allen, Miss. Elisabeth Walton  29.0000  female
1                      Allison, Master. Hudson Trevor   0.9167    male
2                        Allison, Miss. Helen Loraine   2.0000  female
3                Allison, Mr. Hudson Joshua Creighton  30.0000    male
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000  female
...                                               ...      ...     ...
1304                             Zabour, Miss. Hileni  14.5000  female
1305                            Zabour, Miss. Thamine      NaN  female
1306                        Zakarian, Mr. Mapriededer  26.5000    male
1307                              Zakarian, Mr. Ortin  27.0000    male
1308                               Zimmerman, Mr. Leo  29.0000    male

[1309 rows x 3 columns]

In [295]:
# but i loc you need to write collumn name
df.loc[1:10,("name","sex")]

                                               name     sex
1                    Allison, Master. Hudson Trevor    male
2                      Allison, Miss. Helen Loraine  female
3              Allison, Mr. Hudson Joshua Creighton    male
4   Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female
5                               Anderson, Mr. Harry    male
6                 Andrews, Miss. Kornelia Theodosia  female
7                            Andrews, Mr. Thomas Jr    male
8     Appleton, Mrs. Edward Dale (Charlotte Lamson)  female
9                           Artagaveytia, Mr. Ramon    male
10                           Astor, Col. John Jacob    male

**Filtering**

In [296]:
#we use boolean operation for filtering
males_df=df[df["sex"]=="male"]
males_df

,pclass,survived,name,sex,age,fare,body
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,151.5500,NaN
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,151.5500,135.0
5,1,1,"Anderson, Mr. Harry",male,48.0000,26.5500,NaN
7,1,0,"Andrews, Mr. Thomas Jr",male,39.0000,0.0000,NaN
9,1,0,"Artagaveytia, Mr. Ramon",male,71.0000,49.5042,22.0
...,...,...,...,...,...,...,...
1302,3,0,"Yousif, Mr. Wazli",male,NaN,7.2250,NaN
1303,3,0,"Yousseff, Mr. Gerious",male,NaN,14.4583,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,7.2250,304.0
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,7.2250,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,7.8750,NaN

In [298]:
#fetch all the females and who survived
females_df=df[(df["sex"]=="female") & (df["survived"]==1)]
females_df

,pclass,survived,name,sex,age,fare,body
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,211.3375,NaN
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,77.9583,NaN
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,51.4792,NaN
11,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,227.5250,NaN
12,1,1,"Aubart, Mme. Leontine Pauline",female,24.0,69.3000,NaN
...,...,...,...,...,...,...,...
1260,3,1,"Turja, Miss. Anna Sofia",female,18.0,9.8417,NaN
1261,3,1,"Turkula, Mrs. (Hedwig)",female,63.0,9.5875,NaN
1286,3,1,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,7.2292,NaN
1290,3,1,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,7.0000,NaN
1300,3,1,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,14.4542,NaN

In [301]:
df.isnull()

      pclass  survived   name    sex    age   fare   body
0      False     False  False  False  False  False   True
1      False     False  False  False  False  False   True
2      False     False  False  False  False  False   True
3      False     False  False  False  False  False  False
4      False     False  False  False  False  False   True
...      ...       ...    ...    ...    ...    ...    ...
1304   False     False  False  False  False  False  False
1305   False     False  False  False   True  False   True
1306   False     False  False  False  False  False  False
1307   False     False  False  False  False  False   True
1308   False     False  False  False  False  False   True

[1309 rows x 7 columns]

In [305]:
#to rename the column
df.rename(columns={"sex":"gender"},inplace=True)

In [306]:
df

,pclass,survived,name,gender,age,fare,body
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,211.3375,NaN
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,151.5500,NaN
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,151.5500,NaN
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,151.5500,135.0
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,151.5500,NaN
...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,14.4542,328.0
1305,3,0,"Zabour, Miss. Thamine",female,NaN,14.4542,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,7.2250,304.0
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,7.2250,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,7.8750,NaN

In [307]:
#we also use map() to change the values
# and it is the most imp function for the ml because it is use to change the df values
df["survived"]=df["survived"].map({0:"dead",1:"alive"})
df

,pclass,survived,name,gender,age,fare,body
0,1,alive,"Allen, Miss. Elisabeth Walton",female,29.0000,211.3375,NaN
1,1,alive,"Allison, Master. Hudson Trevor",male,0.9167,151.5500,NaN
2,1,dead,"Allison, Miss. Helen Loraine",female,2.0000,151.5500,NaN
3,1,dead,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,151.5500,135.0
4,1,dead,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,151.5500,NaN
...,...,...,...,...,...,...,...
1304,3,dead,"Zabour, Miss. Hileni",female,14.5000,14.4542,328.0
1305,3,dead,"Zabour, Miss. Thamine",female,NaN,14.4542,NaN
1306,3,dead,"Zakarian, Mr. Mapriededer",male,26.5000,7.2250,304.0
1307,3,dead,"Zakarian, Mr. Ortin",male,27.0000,7.2250,NaN
1308,3,dead,"Zimmerman, Mr. Leo",male,29.0000,7.8750,NaN